/*
 * Generated by Hemlock Compiler
 */

#include "hemlock_runtime.h"
#include <setjmp.h>
#include <string.h>
#include <math.h>
#include <signal.h>
#ifdef _WIN32
#include "hemlock_platform.h"
#else
#include <sys/socket.h>
#include <sys/un.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <poll.h>
#include <sys/mman.h>
#endif

// Signal constants
#define SIGINT_VAL 2
#define SIGTERM_VAL 15
#define SIGHUP_VAL 1
#define SIGQUIT_VAL 3
#define SIGABRT_VAL 6
#define SIGUSR1_VAL 10
#define SIGUSR2_VAL 12
#define SIGALRM_VAL 14
#define SIGCHLD_VAL 17
#define SIGPIPE_VAL 13
#define SIGCONT_VAL 18
#define SIGSTOP_VAL 19
#define SIGTSTP_VAL 20

// Built-in globals
static HmlValue _main_args = {0};

// Closure forward declarations
HmlValue hml_fn_anon_8(HmlClosureEnv *_closure_env);
HmlValue hml_fn_anon_7(HmlClosureEnv *_closure_env, HmlValue advice);
HmlValue hml_fn_anon_6(HmlClosureEnv *_closure_env);
HmlValue hml_fn_anon_5(HmlClosureEnv *_closure_env, HmlValue offset, HmlValue val);
HmlValue hml_fn_anon_4(HmlClosureEnv *_closure_env, HmlValue offset, HmlValue val);
HmlValue hml_fn_anon_3(HmlClosureEnv *_closure_env, HmlValue offset);
HmlValue hml_fn_anon_2(HmlClosureEnv *_closure_env, HmlValue offset);
HmlValue hml_fn_anon_1(HmlClosureEnv *_closure_env, HmlValue offset);
HmlValue hml_fn_anon_0(HmlClosureEnv *_closure_env, HmlValue offset);

// Module global variables
static HmlValue _mod0_mmap_open = {0};
static HmlValue _mod0_mmap_open_anon = {0};
static HmlValue _mod0_mmap_sync = {0};
static HmlValue _mod0_mmap_close = {0};
static HmlValue _mod0_mmap_size = {0};
static HmlValue _mod0_mmap_advise = {0};
static HmlValue _mod0_mmap_protect = {0};
static HmlValue _mod0_PROT_NONE = {0};
static HmlValue _mod0_PROT_READ = {0};
static HmlValue _mod0_PROT_WRITE = {0};
static HmlValue _mod0_PROT_EXEC = {0};
static HmlValue _mod0_MADV_NORMAL = {0};
static HmlValue _mod0_MADV_SEQUENTIAL = {0};
static HmlValue _mod0_MADV_RANDOM = {0};
static HmlValue _mod0_MADV_WILLNEED = {0};
static HmlValue _mod0_MADV_DONTNEED = {0};
static HmlValue _mod0_MappedFile = {0};

// Module function forward declarations
HmlValue _mod0_fn_MappedFile(HmlClosureEnv *_closure_env, HmlValue path, HmlValue mode);

// Module init function declarations
static void _mod0__hml_init(void);

// Named function forward declarations

// Closure implementations
HmlValue hml_fn_anon_0(HmlClosureEnv *_closure_env, HmlValue offset) {
    HmlValue _size = hml_closure_env_get(_closure_env, 0);
    HML_CALL_ENTER();
    HmlValue _tmp39 = offset;
    hml_retain_if_needed(&_tmp39);
    HmlValue _tmp40 = hml_val_i32(0);
    HmlValue _tmp38 = hml_both_i32(_tmp39, _tmp40) ? hml_i32_lt(_tmp39, _tmp40) : (hml_both_i64(_tmp39, _tmp40) ? hml_i64_lt(_tmp39, _tmp40) : hml_binary_op(HML_OP_LESS, _tmp39, _tmp40));
    hml_release_if_needed(&_tmp39);
    hml_release_if_needed(&_tmp40);
    HmlValue _tmp37;
    if (hml_to_bool(_tmp38)) {
        _tmp37 = hml_val_bool(1);
    } else {
        HmlValue _tmp42 = offset;
        hml_retain_if_needed(&_tmp42);
        HmlValue _tmp43 = _size;
        hml_retain_if_needed(&_tmp43);
        HmlValue _tmp41 = hml_both_i32(_tmp42, _tmp43) ? hml_i32_ge(_tmp42, _tmp43) : (hml_both_i64(_tmp42, _tmp43) ? hml_i64_ge(_tmp42, _tmp43) : hml_binary_op(HML_OP_GREATER_EQUAL, _tmp42, _tmp43));
        hml_release_if_needed(&_tmp42);
        hml_release_if_needed(&_tmp43);
        _tmp37 = hml_val_bool(hml_to_bool(_tmp41));
        hml_release_if_needed(&_tmp41);
    }
    hml_release_if_needed(&_tmp38);
    int _tmp44 = hml_to_bool(_tmp37);
    hml_release(&_tmp37);
    if (_tmp44) {
        {
            HmlValue _tmp45 = hml_val_string("MappedFile.read_u8: offset out of bounds");
            hml_throw(_tmp45);
        }
    }
    HmlValue _tmp49 = hml_self;
    hml_retain_if_needed(&_tmp49);
    HmlValue _tmp48 = hml_object_get_field_required(_tmp49, "ptr");
    hml_release(&_tmp49);
    HmlValue _tmp50 = offset;
    hml_retain_if_needed(&_tmp50);
    HmlValue _tmp51 = hml_val_i32(1);
    HmlValue _tmp47 = hml_builtin_ptr_offset(NULL, _tmp48, _tmp50, _tmp51);
    hml_release(&_tmp48);
    hml_release(&_tmp50);
    hml_release(&_tmp51);
    HmlValue _tmp46 = hml_builtin_ptr_read_u8(NULL, _tmp47);
    hml_release(&_tmp47);
    HML_CALL_EXIT();
    return _tmp46;
    hml_release(&_size);
    HML_CALL_EXIT();
    return hml_val_null();
}

HmlValue hml_fn_anon_1(HmlClosureEnv *_closure_env, HmlValue offset) {
    HmlValue _size = hml_closure_env_get(_closure_env, 0);
    HML_CALL_ENTER();
    HmlValue _tmp54 = offset;
    hml_retain_if_needed(&_tmp54);
    HmlValue _tmp55 = hml_val_i32(0);
    HmlValue _tmp53 = hml_both_i32(_tmp54, _tmp55) ? hml_i32_lt(_tmp54, _tmp55) : (hml_both_i64(_tmp54, _tmp55) ? hml_i64_lt(_tmp54, _tmp55) : hml_binary_op(HML_OP_LESS, _tmp54, _tmp55));
    hml_release_if_needed(&_tmp54);
    hml_release_if_needed(&_tmp55);
    HmlValue _tmp52;
    if (hml_to_bool(_tmp53)) {
        _tmp52 = hml_val_bool(1);
    } else {
        HmlValue _tmp58 = offset;
        hml_retain_if_needed(&_tmp58);
        HmlValue _tmp59 = hml_val_i32(4);
        HmlValue _tmp57 = hml_both_i32(_tmp58, _tmp59) ? hml_i32_add(_tmp58, _tmp59) : (hml_both_i64(_tmp58, _tmp59) ? hml_i64_add(_tmp58, _tmp59) : hml_binary_op(HML_OP_ADD, _tmp58, _tmp59));
        hml_release_if_needed(&_tmp58);
        hml_release_if_needed(&_tmp59);
        HmlValue _tmp60 = _size;
        hml_retain_if_needed(&_tmp60);
        HmlValue _tmp56 = hml_both_i32(_tmp57, _tmp60) ? hml_i32_gt(_tmp57, _tmp60) : (hml_both_i64(_tmp57, _tmp60) ? hml_i64_gt(_tmp57, _tmp60) : hml_binary_op(HML_OP_GREATER, _tmp57, _tmp60));
        hml_release_if_needed(&_tmp57);
        hml_release_if_needed(&_tmp60);
        _tmp52 = hml_val_bool(hml_to_bool(_tmp56));
        hml_release_if_needed(&_tmp56);
    }
    hml_release_if_needed(&_tmp53);
    int _tmp61 = hml_to_bool(_tmp52);
    hml_release(&_tmp52);
    if (_tmp61) {
        {
            HmlValue _tmp62 = hml_val_string("MappedFile.read_i32: offset out of bounds");
            hml_throw(_tmp62);
        }
    }
    HmlValue _tmp66 = hml_self;
    hml_retain_if_needed(&_tmp66);
    HmlValue _tmp65 = hml_object_get_field_required(_tmp66, "ptr");
    hml_release(&_tmp66);
    HmlValue _tmp67 = offset;
    hml_retain_if_needed(&_tmp67);
    HmlValue _tmp68 = hml_val_i32(1);
    HmlValue _tmp64 = hml_builtin_ptr_offset(NULL, _tmp65, _tmp67, _tmp68);
    hml_release(&_tmp65);
    hml_release(&_tmp67);
    hml_release(&_tmp68);
    HmlValue _tmp63 = hml_builtin_ptr_read_i32(NULL, _tmp64);
    hml_release(&_tmp64);
    HML_CALL_EXIT();
    return _tmp63;
    hml_release(&_size);
    HML_CALL_EXIT();
    return hml_val_null();
}

HmlValue hml_fn_anon_2(HmlClosureEnv *_closure_env, HmlValue offset) {
    HmlValue _size = hml_closure_env_get(_closure_env, 0);
    HML_CALL_ENTER();
    HmlValue _tmp71 = offset;
    hml_retain_if_needed(&_tmp71);
    HmlValue _tmp72 = hml_val_i32(0);
    HmlValue _tmp70 = hml_both_i32(_tmp71, _tmp72) ? hml_i32_lt(_tmp71, _tmp72) : (hml_both_i64(_tmp71, _tmp72) ? hml_i64_lt(_tmp71, _tmp72) : hml_binary_op(HML_OP_LESS, _tmp71, _tmp72));
    hml_release_if_needed(&_tmp71);
    hml_release_if_needed(&_tmp72);
    HmlValue _tmp69;
    if (hml_to_bool(_tmp70)) {
        _tmp69 = hml_val_bool(1);
    } else {
        HmlValue _tmp75 = offset;
        hml_retain_if_needed(&_tmp75);
        HmlValue _tmp76 = hml_val_i32(8);
        HmlValue _tmp74 = hml_both_i32(_tmp75, _tmp76) ? hml_i32_add(_tmp75, _tmp76) : (hml_both_i64(_tmp75, _tmp76) ? hml_i64_add(_tmp75, _tmp76) : hml_binary_op(HML_OP_ADD, _tmp75, _tmp76));
        hml_release_if_needed(&_tmp75);
        hml_release_if_needed(&_tmp76);
        HmlValue _tmp77 = _size;
        hml_retain_if_needed(&_tmp77);
        HmlValue _tmp73 = hml_both_i32(_tmp74, _tmp77) ? hml_i32_gt(_tmp74, _tmp77) : (hml_both_i64(_tmp74, _tmp77) ? hml_i64_gt(_tmp74, _tmp77) : hml_binary_op(HML_OP_GREATER, _tmp74, _tmp77));
        hml_release_if_needed(&_tmp74);
        hml_release_if_needed(&_tmp77);
        _tmp69 = hml_val_bool(hml_to_bool(_tmp73));
        hml_release_if_needed(&_tmp73);
    }
    hml_release_if_needed(&_tmp70);
    int _tmp78 = hml_to_bool(_tmp69);
    hml_release(&_tmp69);
    if (_tmp78) {
        {
            HmlValue _tmp79 = hml_val_string("MappedFile.read_i64: offset out of bounds");
            hml_throw(_tmp79);
        }
    }
    HmlValue _tmp83 = hml_self;
    hml_retain_if_needed(&_tmp83);
    HmlValue _tmp82 = hml_object_get_field_required(_tmp83, "ptr");
    hml_release(&_tmp83);
    HmlValue _tmp84 = offset;
    hml_retain_if_needed(&_tmp84);
    HmlValue _tmp85 = hml_val_i32(1);
    HmlValue _tmp81 = hml_builtin_ptr_offset(NULL, _tmp82, _tmp84, _tmp85);
    hml_release(&_tmp82);
    hml_release(&_tmp84);
    hml_release(&_tmp85);
    HmlValue _tmp80 = hml_builtin_ptr_read_i64(NULL, _tmp81);
    hml_release(&_tmp81);
    HML_CALL_EXIT();
    return _tmp80;
    hml_release(&_size);
    HML_CALL_EXIT();
    return hml_val_null();
}

HmlValue hml_fn_anon_3(HmlClosureEnv *_closure_env, HmlValue offset) {
    HmlValue _size = hml_closure_env_get(_closure_env, 0);
    HML_CALL_ENTER();
    HmlValue _tmp88 = offset;
    hml_retain_if_needed(&_tmp88);
    HmlValue _tmp89 = hml_val_i32(0);
    HmlValue _tmp87 = hml_both_i32(_tmp88, _tmp89) ? hml_i32_lt(_tmp88, _tmp89) : (hml_both_i64(_tmp88, _tmp89) ? hml_i64_lt(_tmp88, _tmp89) : hml_binary_op(HML_OP_LESS, _tmp88, _tmp89));
    hml_release_if_needed(&_tmp88);
    hml_release_if_needed(&_tmp89);
    HmlValue _tmp86;
    if (hml_to_bool(_tmp87)) {
        _tmp86 = hml_val_bool(1);
    } else {
        HmlValue _tmp92 = offset;
        hml_retain_if_needed(&_tmp92);
        HmlValue _tmp93 = hml_val_i32(8);
        HmlValue _tmp91 = hml_both_i32(_tmp92, _tmp93) ? hml_i32_add(_tmp92, _tmp93) : (hml_both_i64(_tmp92, _tmp93) ? hml_i64_add(_tmp92, _tmp93) : hml_binary_op(HML_OP_ADD, _tmp92, _tmp93));
        hml_release_if_needed(&_tmp92);
        hml_release_if_needed(&_tmp93);
        HmlValue _tmp94 = _size;
        hml_retain_if_needed(&_tmp94);
        HmlValue _tmp90 = hml_both_i32(_tmp91, _tmp94) ? hml_i32_gt(_tmp91, _tmp94) : (hml_both_i64(_tmp91, _tmp94) ? hml_i64_gt(_tmp91, _tmp94) : hml_binary_op(HML_OP_GREATER, _tmp91, _tmp94));
        hml_release_if_needed(&_tmp91);
        hml_release_if_needed(&_tmp94);
        _tmp86 = hml_val_bool(hml_to_bool(_tmp90));
        hml_release_if_needed(&_tmp90);
    }
    hml_release_if_needed(&_tmp87);
    int _tmp95 = hml_to_bool(_tmp86);
    hml_release(&_tmp86);
    if (_tmp95) {
        {
            HmlValue _tmp96 = hml_val_string("MappedFile.read_f64: offset out of bounds");
            hml_throw(_tmp96);
        }
    }
    HmlValue _tmp100 = hml_self;
    hml_retain_if_needed(&_tmp100);
    HmlValue _tmp99 = hml_object_get_field_required(_tmp100, "ptr");
    hml_release(&_tmp100);
    HmlValue _tmp101 = offset;
    hml_retain_if_needed(&_tmp101);
    HmlValue _tmp102 = hml_val_i32(1);
    HmlValue _tmp98 = hml_builtin_ptr_offset(NULL, _tmp99, _tmp101, _tmp102);
    hml_release(&_tmp99);
    hml_release(&_tmp101);
    hml_release(&_tmp102);
    HmlValue _tmp97 = hml_builtin_ptr_read_f64(NULL, _tmp98);
    hml_release(&_tmp98);
    HML_CALL_EXIT();
    return _tmp97;
    hml_release(&_size);
    HML_CALL_EXIT();
    return hml_val_null();
}

HmlValue hml_fn_anon_4(HmlClosureEnv *_closure_env, HmlValue offset, HmlValue val) {
    HmlValue _v__mode = hml_closure_env_get(_closure_env, 7);
    HmlValue _size = hml_closure_env_get(_closure_env, 0);
    HML_CALL_ENTER();
    HmlValue _tmp104 = _v__mode;
    hml_retain_if_needed(&_tmp104);
    HmlValue _tmp105 = hml_val_string("rw");
    HmlValue _tmp103 = hml_both_i32(_tmp104, _tmp105) ? hml_i32_ne(_tmp104, _tmp105) : (hml_both_i64(_tmp104, _tmp105) ? hml_i64_ne(_tmp104, _tmp105) : hml_binary_op(HML_OP_NOT_EQUAL, _tmp104, _tmp105));
    hml_release_if_needed(&_tmp104);
    hml_release_if_needed(&_tmp105);
    int _tmp106 = hml_to_bool(_tmp103);
    hml_release(&_tmp103);
    if (_tmp106) {
        {
            HmlValue _tmp107 = hml_val_string("MappedFile.write_u8: file not opened in rw mode");
            hml_throw(_tmp107);
        }
    }
    HmlValue _tmp110 = offset;
    hml_retain_if_needed(&_tmp110);
    HmlValue _tmp111 = hml_val_i32(0);
    HmlValue _tmp109 = hml_both_i32(_tmp110, _tmp111) ? hml_i32_lt(_tmp110, _tmp111) : (hml_both_i64(_tmp110, _tmp111) ? hml_i64_lt(_tmp110, _tmp111) : hml_binary_op(HML_OP_LESS, _tmp110, _tmp111));
    hml_release_if_needed(&_tmp110);
    hml_release_if_needed(&_tmp111);
    HmlValue _tmp108;
    if (hml_to_bool(_tmp109)) {
        _tmp108 = hml_val_bool(1);
    } else {
        HmlValue _tmp113 = offset;
        hml_retain_if_needed(&_tmp113);
        HmlValue _tmp114 = _size;
        hml_retain_if_needed(&_tmp114);
        HmlValue _tmp112 = hml_both_i32(_tmp113, _tmp114) ? hml_i32_ge(_tmp113, _tmp114) : (hml_both_i64(_tmp113, _tmp114) ? hml_i64_ge(_tmp113, _tmp114) : hml_binary_op(HML_OP_GREATER_EQUAL, _tmp113, _tmp114));
        hml_release_if_needed(&_tmp113);
        hml_release_if_needed(&_tmp114);
        _tmp108 = hml_val_bool(hml_to_bool(_tmp112));
        hml_release_if_needed(&_tmp112);
    }
    hml_release_if_needed(&_tmp109);
    int _tmp115 = hml_to_bool(_tmp108);
    hml_release(&_tmp108);
    if (_tmp115) {
        {
            HmlValue _tmp116 = hml_val_string("MappedFile.write_u8: offset out of bounds");
            hml_throw(_tmp116);
        }
    }
    HmlValue _tmp120 = hml_self;
    hml_retain_if_needed(&_tmp120);
    HmlValue _tmp119 = hml_object_get_field_required(_tmp120, "ptr");
    hml_release(&_tmp120);
    HmlValue _tmp121 = offset;
    hml_retain_if_needed(&_tmp121);
    HmlValue _tmp122 = hml_val_i32(1);
    HmlValue _tmp118 = hml_builtin_ptr_offset(NULL, _tmp119, _tmp121, _tmp122);
    hml_release(&_tmp119);
    hml_release(&_tmp121);
    hml_release(&_tmp122);
    HmlValue _tmp123 = val;
    hml_retain_if_needed(&_tmp123);
    HmlValue _tmp117 = hml_builtin_ptr_write_u8(NULL, _tmp118, _tmp123);
    hml_release(&_tmp118);
    hml_release(&_tmp123);
    hml_release(&_tmp117);
    hml_release(&_v__mode);
    hml_release(&_size);
    HML_CALL_EXIT();
    return hml_val_null();
}

HmlValue hml_fn_anon_5(HmlClosureEnv *_closure_env, HmlValue offset, HmlValue val) {
    HmlValue _v__mode = hml_closure_env_get(_closure_env, 7);
    HmlValue _size = hml_closure_env_get(_closure_env, 0);
    HML_CALL_ENTER();
    HmlValue _tmp125 = _v__mode;
    hml_retain_if_needed(&_tmp125);
    HmlValue _tmp126 = hml_val_string("rw");
    HmlValue _tmp124 = hml_both_i32(_tmp125, _tmp126) ? hml_i32_ne(_tmp125, _tmp126) : (hml_both_i64(_tmp125, _tmp126) ? hml_i64_ne(_tmp125, _tmp126) : hml_binary_op(HML_OP_NOT_EQUAL, _tmp125, _tmp126));
    hml_release_if_needed(&_tmp125);
    hml_release_if_needed(&_tmp126);
    int _tmp127 = hml_to_bool(_tmp124);
    hml_release(&_tmp124);
    if (_tmp127) {
        {
            HmlValue _tmp128 = hml_val_string("MappedFile.write_i32: file not opened in rw mode");
            hml_throw(_tmp128);
        }
    }
    HmlValue _tmp131 = offset;
    hml_retain_if_needed(&_tmp131);
    HmlValue _tmp132 = hml_val_i32(0);
    HmlValue _tmp130 = hml_both_i32(_tmp131, _tmp132) ? hml_i32_lt(_tmp131, _tmp132) : (hml_both_i64(_tmp131, _tmp132) ? hml_i64_lt(_tmp131, _tmp132) : hml_binary_op(HML_OP_LESS, _tmp131, _tmp132));
    hml_release_if_needed(&_tmp131);
    hml_release_if_needed(&_tmp132);
    HmlValue _tmp129;
    if (hml_to_bool(_tmp130)) {
        _tmp129 = hml_val_bool(1);
    } else {
        HmlValue _tmp135 = offset;
        hml_retain_if_needed(&_tmp135);
        HmlValue _tmp136 = hml_val_i32(4);
        HmlValue _tmp134 = hml_both_i32(_tmp135, _tmp136) ? hml_i32_add(_tmp135, _tmp136) : (hml_both_i64(_tmp135, _tmp136) ? hml_i64_add(_tmp135, _tmp136) : hml_binary_op(HML_OP_ADD, _tmp135, _tmp136));
        hml_release_if_needed(&_tmp135);
        hml_release_if_needed(&_tmp136);
        HmlValue _tmp137 = _size;
        hml_retain_if_needed(&_tmp137);
        HmlValue _tmp133 = hml_both_i32(_tmp134, _tmp137) ? hml_i32_gt(_tmp134, _tmp137) : (hml_both_i64(_tmp134, _tmp137) ? hml_i64_gt(_tmp134, _tmp137) : hml_binary_op(HML_OP_GREATER, _tmp134, _tmp137));
        hml_release_if_needed(&_tmp134);
        hml_release_if_needed(&_tmp137);
        _tmp129 = hml_val_bool(hml_to_bool(_tmp133));
        hml_release_if_needed(&_tmp133);
    }
    hml_release_if_needed(&_tmp130);
    int _tmp138 = hml_to_bool(_tmp129);
    hml_release(&_tmp129);
    if (_tmp138) {
        {
            HmlValue _tmp139 = hml_val_string("MappedFile.write_i32: offset out of bounds");
            hml_throw(_tmp139);
        }
    }
    HmlValue _tmp143 = hml_self;
    hml_retain_if_needed(&_tmp143);
    HmlValue _tmp142 = hml_object_get_field_required(_tmp143, "ptr");
    hml_release(&_tmp143);
    HmlValue _tmp144 = offset;
    hml_retain_if_needed(&_tmp144);
    HmlValue _tmp145 = hml_val_i32(1);
    HmlValue _tmp141 = hml_builtin_ptr_offset(NULL, _tmp142, _tmp144, _tmp145);
    hml_release(&_tmp142);
    hml_release(&_tmp144);
    hml_release(&_tmp145);
    HmlValue _tmp146 = val;
    hml_retain_if_needed(&_tmp146);
    HmlValue _tmp140 = hml_builtin_ptr_write_i32(NULL, _tmp141, _tmp146);
    hml_release(&_tmp141);
    hml_release(&_tmp146);
    hml_release(&_tmp140);
    hml_release(&_v__mode);
    hml_release(&_size);
    HML_CALL_EXIT();
    return hml_val_null();
}

HmlValue hml_fn_anon_6(HmlClosureEnv *_closure_env) {
    HML_CALL_ENTER();
    HmlValue _tmp149 = hml_self;
    hml_retain_if_needed(&_tmp149);
    HmlValue _tmp148 = hml_object_get_field_required(_tmp149, "ptr");
    hml_release(&_tmp149);
    HmlValue _tmp147 = _mod0_fn_mmap_sync(NULL, _tmp148);
    hml_release(&_tmp148);
    HML_CALL_EXIT();
    return _tmp147;
    HML_CALL_EXIT();
    return hml_val_null();
}

HmlValue hml_fn_anon_7(HmlClosureEnv *_closure_env, HmlValue advice) {
    HML_CALL_ENTER();
    HmlValue _tmp152 = hml_self;
    hml_retain_if_needed(&_tmp152);
    HmlValue _tmp151 = hml_object_get_field_required(_tmp152, "ptr");
    hml_release(&_tmp152);
    HmlValue _tmp153 = advice;
    hml_retain_if_needed(&_tmp153);
    HmlValue _tmp150 = _mod0_fn_mmap_advise(NULL, _tmp151, _tmp153);
    hml_release(&_tmp151);
    hml_release(&_tmp153);
    HML_CALL_EXIT();
    return _tmp150;
    HML_CALL_EXIT();
    return hml_val_null();
}

HmlValue hml_fn_anon_8(HmlClosureEnv *_closure_env) {
    HML_CALL_ENTER();
    HmlValue _tmp156 = hml_self;
    hml_retain_if_needed(&_tmp156);
    HmlValue _tmp155 = hml_object_get_field_required(_tmp156, "ptr");
    hml_release(&_tmp156);
    HmlValue _tmp154 = _mod0_fn_mmap_close(NULL, _tmp155);
    hml_release(&_tmp155);
    HML_CALL_EXIT();
    return _tmp154;
    HML_CALL_EXIT();
    return hml_val_null();
}

// Module function implementations
HmlValue _mod0_fn_MappedFile(HmlClosureEnv *_closure_env, HmlValue path, HmlValue mode) {
    (void)_closure_env;
    if (mode.type == HML_VAL_NULL) {
        HmlValue _tmp0 = hml_val_string("r");
        mode = _tmp0;
    }
    HmlClosureEnv *_shared_env_1 = hml_closure_env_new(13);
    HmlValue _tmp3 = path;
    hml_retain_if_needed(&_tmp3);
    HmlValue _tmp4 = mode;
    hml_retain_if_needed(&_tmp4);
    HmlValue _tmp2 = _mod0_fn_mmap_open(NULL, _tmp3, _tmp4);
    hml_release(&_tmp3);
    hml_release(&_tmp4);
    HmlValue _ptr = _tmp2;
    HmlValue _tmp6 = _ptr;
    hml_retain_if_needed(&_tmp6);
    HmlValue _tmp7 = hml_val_null();
    HmlValue _tmp5 = hml_both_i32(_tmp6, _tmp7) ? hml_i32_eq(_tmp6, _tmp7) : (hml_both_i64(_tmp6, _tmp7) ? hml_i64_eq(_tmp6, _tmp7) : hml_binary_op(HML_OP_EQUAL, _tmp6, _tmp7));
    hml_release_if_needed(&_tmp6);
    hml_release_if_needed(&_tmp7);
    int _tmp8 = hml_to_bool(_tmp5);
    hml_release(&_tmp5);
    if (_tmp8) {
        {
            HmlValue _tmp10 = hml_val_string("MappedFile: failed to map '");
            HmlValue _tmp11 = path;
            hml_retain_if_needed(&_tmp11);
            HmlValue _tmp12 = hml_val_string("'");
            HmlValue _tmp9 = hml_string_concat3(_tmp10, _tmp11, _tmp12);
            hml_release_if_needed(&_tmp10);
            hml_release_if_needed(&_tmp11);
            hml_release_if_needed(&_tmp12);
            hml_throw(_tmp9);
        }
    }
    HmlValue _tmp14 = _ptr;
    hml_retain_if_needed(&_tmp14);
    HmlValue _tmp13 = _mod0_fn_mmap_size(NULL, _tmp14);
    hml_release(&_tmp14);
    HmlValue _size = _tmp13;
    hml_closure_env_set(_shared_env_1, 0, _size);
    HmlValue _tmp15 = mode;
    hml_retain_if_needed(&_tmp15);
    HmlValue _v__mode = _tmp15;
    hml_closure_env_set(_shared_env_1, 7, _v__mode);
    HmlValue _tmp16 = hml_val_object();
    HmlValue _tmp17 = _ptr;
    hml_retain_if_needed(&_tmp17);
    hml_object_set_field(_tmp16, "ptr", _tmp17);
    hml_release(&_tmp17);
    HmlValue _tmp18 = hml_closure_env_get(_shared_env_1, 0);
    hml_object_set_field(_tmp16, "size", _tmp18);
    hml_release(&_tmp18);
    hml_closure_env_set(_shared_env_1, 0, _size);
    hml_closure_env_retain(_shared_env_1);
    HmlValue _tmp19 = hml_val_function_with_env_rest((void*)hml_fn_anon_0, (void*)_shared_env_1, 1, 1, 0, 0);
    const char *_param_names20[1] = {
"offset"    };
    hml_function_set_param_names(_tmp19, _param_names20, 1);
    hml_object_set_field(_tmp16, "read_u8", _tmp19);
    hml_release(&_tmp19);
    hml_closure_env_set(_shared_env_1, 0, _size);
    hml_closure_env_retain(_shared_env_1);
    HmlValue _tmp21 = hml_val_function_with_env_rest((void*)hml_fn_anon_1, (void*)_shared_env_1, 1, 1, 0, 0);
    const char *_param_names22[1] = {
"offset"    };
    hml_function_set_param_names(_tmp21, _param_names22, 1);
    hml_object_set_field(_tmp16, "read_i32", _tmp21);
    hml_release(&_tmp21);
    hml_closure_env_set(_shared_env_1, 0, _size);
    hml_closure_env_retain(_shared_env_1);
    HmlValue _tmp23 = hml_val_function_with_env_rest((void*)hml_fn_anon_2, (void*)_shared_env_1, 1, 1, 0, 0);
    const char *_param_names24[1] = {
"offset"    };
    hml_function_set_param_names(_tmp23, _param_names24, 1);
    hml_object_set_field(_tmp16, "read_i64", _tmp23);
    hml_release(&_tmp23);
    hml_closure_env_set(_shared_env_1, 0, _size);
    hml_closure_env_retain(_shared_env_1);
    HmlValue _tmp25 = hml_val_function_with_env_rest((void*)hml_fn_anon_3, (void*)_shared_env_1, 1, 1, 0, 0);
    const char *_param_names26[1] = {
"offset"    };
    hml_function_set_param_names(_tmp25, _param_names26, 1);
    hml_object_set_field(_tmp16, "read_f64", _tmp25);
    hml_release(&_tmp25);
    hml_closure_env_set(_shared_env_1, 7, _v__mode);
    hml_closure_env_set(_shared_env_1, 0, _size);
    hml_closure_env_retain(_shared_env_1);
    HmlValue _tmp27 = hml_val_function_with_env_rest((void*)hml_fn_anon_4, (void*)_shared_env_1, 2, 2, 0, 0);
    const char *_param_names28[2] = {
"offset", "val"    };
    hml_function_set_param_names(_tmp27, _param_names28, 2);
    hml_object_set_field(_tmp16, "write_u8", _tmp27);
    hml_release(&_tmp27);
    hml_closure_env_set(_shared_env_1, 7, _v__mode);
    hml_closure_env_set(_shared_env_1, 0, _size);
    hml_closure_env_retain(_shared_env_1);
    HmlValue _tmp29 = hml_val_function_with_env_rest((void*)hml_fn_anon_5, (void*)_shared_env_1, 2, 2, 0, 0);
    const char *_param_names30[2] = {
"offset", "val"    };
    hml_function_set_param_names(_tmp29, _param_names30, 2);
    hml_object_set_field(_tmp16, "write_i32", _tmp29);
    hml_release(&_tmp29);
    HmlValue _tmp31 = hml_val_function_rest((void*)hml_fn_anon_6, 0, 0, 0, 0);
    hml_object_set_field(_tmp16, "sync", _tmp31);
    hml_release(&_tmp31);
    HmlValue _tmp32 = hml_val_function_rest((void*)hml_fn_anon_7, 1, 1, 0, 0);
    const char *_param_names33[1] = {
"advice"    };
    hml_function_set_param_names(_tmp32, _param_names33, 1);
    hml_object_set_field(_tmp16, "advise", _tmp32);
    hml_release(&_tmp32);
    HmlValue _tmp34 = hml_val_function_rest((void*)hml_fn_anon_8, 0, 0, 0, 0);
    hml_object_set_field(_tmp16, "close", _tmp34);
    hml_release(&_tmp34);
    hml_release(&_ptr);
    hml_release(&_size);
    hml_release(&_v__mode);
    hml_closure_env_release(_shared_env_1);
    HML_CALL_EXIT();
    return _tmp16;
    hml_release(&_ptr);
    hml_release(&_size);
    hml_release(&_v__mode);
    hml_closure_env_release(_shared_env_1);
    return hml_val_null();
}

// Module init functions
// Module init: /home/user/hemlock/stdlib/mmap.hml
static int _mod0__hml_init_done = 0;
static void _mod0__hml_init(void) {
    if (_mod0__hml_init_done) return;
    _mod0__hml_init_done = 1;


    HmlValue _tmp157 = hml_val_function((void*)hml_builtin_mmap_open, 1, 2, 0);
    hml_retain_if_needed(&_tmp157);
    _mod0_mmap_open = _tmp157;
    HmlValue _tmp158 = hml_val_function((void*)hml_builtin_mmap_open_anon, 1, 1, 0);
    hml_retain_if_needed(&_tmp158);
    _mod0_mmap_open_anon = _tmp158;
    HmlValue _tmp159 = hml_val_function((void*)hml_builtin_mmap_sync, 1, 1, 0);
    hml_retain_if_needed(&_tmp159);
    _mod0_mmap_sync = _tmp159;
    HmlValue _tmp160 = hml_val_function((void*)hml_builtin_mmap_close, 1, 1, 0);
    hml_retain_if_needed(&_tmp160);
    _mod0_mmap_close = _tmp160;
    HmlValue _tmp161 = hml_val_function((void*)hml_builtin_mmap_size, 1, 1, 0);
    hml_retain_if_needed(&_tmp161);
    _mod0_mmap_size = _tmp161;
    HmlValue _tmp162 = hml_val_function((void*)hml_builtin_mmap_advise, 2, 2, 0);
    hml_retain_if_needed(&_tmp162);
    _mod0_mmap_advise = _tmp162;
    HmlValue _tmp163 = hml_val_function((void*)hml_builtin_mmap_protect, 2, 2, 0);
    hml_retain_if_needed(&_tmp163);
    _mod0_mmap_protect = _tmp163;
    HmlValue _tmp164 = hml_val_i32(PROT_NONE);
    hml_retain_if_needed(&_tmp164);
    _mod0_PROT_NONE = _tmp164;
    HmlValue _tmp165 = hml_val_i32(PROT_READ);
    hml_retain_if_needed(&_tmp165);
    _mod0_PROT_READ = _tmp165;
    HmlValue _tmp166 = hml_val_i32(PROT_WRITE);
    hml_retain_if_needed(&_tmp166);
    _mod0_PROT_WRITE = _tmp166;
    HmlValue _tmp167 = hml_val_i32(PROT_EXEC);
    hml_retain_if_needed(&_tmp167);
    _mod0_PROT_EXEC = _tmp167;
    HmlValue _tmp168 = hml_val_i32(MADV_NORMAL);
    hml_retain_if_needed(&_tmp168);
    _mod0_MADV_NORMAL = _tmp168;
    HmlValue _tmp169 = hml_val_i32(MADV_SEQUENTIAL);
    hml_retain_if_needed(&_tmp169);
    _mod0_MADV_SEQUENTIAL = _tmp169;
    HmlValue _tmp170 = hml_val_i32(MADV_RANDOM);
    hml_retain_if_needed(&_tmp170);
    _mod0_MADV_RANDOM = _tmp170;
    HmlValue _tmp171 = hml_val_i32(MADV_WILLNEED);
    hml_retain_if_needed(&_tmp171);
    _mod0_MADV_WILLNEED = _tmp171;
    HmlValue _tmp172 = hml_val_i32(MADV_DONTNEED);
    hml_retain_if_needed(&_tmp172);
    _mod0_MADV_DONTNEED = _tmp172;
    _mod0_MappedFile = hml_val_function((void*)_mod0_fn_MappedFile, 2, 1, 0);
}

// Named function implementations
int main(int argc, char **argv) {
    hml_runtime_init(argc, argv);

    _main_args = hml_get_args();

    _mod0__hml_init();


    // Import from "@stdlib/mmap"
    HmlValue _tmp36 = hml_val_string("ok");
    hml_print_value(_tmp36);
    hml_release(&_tmp36);
    hml_print_newline();
    HmlValue _tmp35 = hml_val_null();
    hml_release(&_tmp35);

    // Release top-level static variables
    {
        HmlValue *_statics[] = {
            &_main_args,
        };
        hml_break_cycles(_statics, 1);
        hml_release_statics(_statics, 1);
    }

    hml_runtime_cleanup();
    return 0;
}
