/*
 * Generated by Hemlock Compiler
 */

#include "hemlock_runtime.h"
#include <setjmp.h>
#include <signal.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <poll.h>
#include <sys/mman.h>

// Signal constants
#define SIGINT_VAL 2
#define SIGTERM_VAL 15
#define SIGHUP_VAL 1
#define SIGQUIT_VAL 3
#define SIGABRT_VAL 6
#define SIGUSR1_VAL 10
#define SIGUSR2_VAL 12
#define SIGALRM_VAL 14
#define SIGCHLD_VAL 17
#define SIGPIPE_VAL 13
#define SIGCONT_VAL 18
#define SIGSTOP_VAL 19
#define SIGTSTP_VAL 20

// Built-in globals
static HmlValue _main_args = {0};

// Top-level function variables (static for closure access)
static HmlValue _main_MappedFile = {0};

// Top-level variables (static for function access)
static HmlValue _main_mmap_open = {0};
static HmlValue _main_mmap_open_anon = {0};
static HmlValue _main_mmap_sync = {0};
static HmlValue _main_mmap_close = {0};
static HmlValue _main_mmap_size = {0};
static HmlValue _main_mmap_advise = {0};
static HmlValue _main_mmap_protect = {0};
static HmlValue _main_PROT_NONE = {0};
static HmlValue _main_PROT_READ = {0};
static HmlValue _main_PROT_WRITE = {0};
static HmlValue _main_PROT_EXEC = {0};
static HmlValue _main_MADV_NORMAL = {0};
static HmlValue _main_MADV_SEQUENTIAL = {0};
static HmlValue _main_MADV_RANDOM = {0};
static HmlValue _main_MADV_WILLNEED = {0};
static HmlValue _main_MADV_DONTNEED = {0};

// Closure forward declarations
HmlValue hml_fn_anon_18(HmlClosureEnv *_closure_env);
HmlValue hml_fn_anon_17(HmlClosureEnv *_closure_env, HmlValue advice);
HmlValue hml_fn_anon_16(HmlClosureEnv *_closure_env);
HmlValue hml_fn_anon_15(HmlClosureEnv *_closure_env, HmlValue offset, HmlValue val);
HmlValue hml_fn_anon_14(HmlClosureEnv *_closure_env, HmlValue offset, HmlValue val);
HmlValue hml_fn_anon_13(HmlClosureEnv *_closure_env, HmlValue offset);
HmlValue hml_fn_anon_12(HmlClosureEnv *_closure_env, HmlValue offset);
HmlValue hml_fn_anon_11(HmlClosureEnv *_closure_env, HmlValue offset);
HmlValue hml_fn_anon_10(HmlClosureEnv *_closure_env, HmlValue offset);
HmlValue hml_fn_anon_9(HmlClosureEnv *_closure_env, HmlValue path, HmlValue mode);
HmlValue hml_fn_anon_8(HmlClosureEnv *_closure_env);
HmlValue hml_fn_anon_7(HmlClosureEnv *_closure_env, HmlValue advice);
HmlValue hml_fn_anon_6(HmlClosureEnv *_closure_env);
HmlValue hml_fn_anon_5(HmlClosureEnv *_closure_env, HmlValue offset, HmlValue val);
HmlValue hml_fn_anon_4(HmlClosureEnv *_closure_env, HmlValue offset, HmlValue val);
HmlValue hml_fn_anon_3(HmlClosureEnv *_closure_env, HmlValue offset);
HmlValue hml_fn_anon_2(HmlClosureEnv *_closure_env, HmlValue offset);
HmlValue hml_fn_anon_1(HmlClosureEnv *_closure_env, HmlValue offset);
HmlValue hml_fn_anon_0(HmlClosureEnv *_closure_env, HmlValue offset);

// Named function forward declarations
HmlValue hml_fn_MappedFile(HmlClosureEnv *_closure_env, HmlValue path, HmlValue mode);

// Closure implementations
HmlValue hml_fn_anon_0(HmlClosureEnv *_closure_env, HmlValue offset) {
    HmlValue _size = hml_closure_env_get(_closure_env, 0);
    HML_CALL_ENTER();
    HmlValue _tmp59 = offset;
    hml_retain_if_needed(&_tmp59);
    HmlValue _tmp60 = hml_val_i32(0);
    HmlValue _tmp58 = hml_both_i32(_tmp59, _tmp60) ? hml_i32_lt(_tmp59, _tmp60) : (hml_both_i64(_tmp59, _tmp60) ? hml_i64_lt(_tmp59, _tmp60) : hml_binary_op(HML_OP_LESS, _tmp59, _tmp60));
    hml_release_if_needed(&_tmp59);
    hml_release_if_needed(&_tmp60);
    HmlValue _tmp57;
    if (hml_to_bool(_tmp58)) {
        _tmp57 = hml_val_bool(1);
    } else {
        HmlValue _tmp62 = offset;
        hml_retain_if_needed(&_tmp62);
        HmlValue _tmp63 = _size;
        hml_retain_if_needed(&_tmp63);
        HmlValue _tmp61 = hml_both_i32(_tmp62, _tmp63) ? hml_i32_ge(_tmp62, _tmp63) : (hml_both_i64(_tmp62, _tmp63) ? hml_i64_ge(_tmp62, _tmp63) : hml_binary_op(HML_OP_GREATER_EQUAL, _tmp62, _tmp63));
        hml_release_if_needed(&_tmp62);
        hml_release_if_needed(&_tmp63);
        _tmp57 = hml_val_bool(hml_to_bool(_tmp61));
        hml_release_if_needed(&_tmp61);
    }
    hml_release_if_needed(&_tmp58);
    int _tmp64 = hml_to_bool(_tmp57);
    hml_release(&_tmp57);
    if (_tmp64) {
        {
            HmlValue _tmp65 = hml_val_string("MappedFile.read_u8: offset out of bounds");
            hml_throw(_tmp65);
        }
    }
    HmlValue _tmp69 = hml_self;
    hml_retain_if_needed(&_tmp69);
    HmlValue _tmp68 = hml_object_get_field_required(_tmp69, "ptr");
    hml_release(&_tmp69);
    HmlValue _tmp70 = offset;
    hml_retain_if_needed(&_tmp70);
    HmlValue _tmp71 = hml_val_i32(1);
    HmlValue _tmp67 = hml_builtin_ptr_offset(NULL, _tmp68, _tmp70, _tmp71);
    hml_release(&_tmp68);
    hml_release(&_tmp70);
    hml_release(&_tmp71);
    HmlValue _tmp66 = hml_builtin_ptr_read_u8(NULL, _tmp67);
    hml_release(&_tmp67);
    HML_CALL_EXIT();
    return _tmp66;
    hml_release(&_size);
    HML_CALL_EXIT();
    return hml_val_null();
}

HmlValue hml_fn_anon_1(HmlClosureEnv *_closure_env, HmlValue offset) {
    HmlValue _size = hml_closure_env_get(_closure_env, 0);
    HML_CALL_ENTER();
    HmlValue _tmp74 = offset;
    hml_retain_if_needed(&_tmp74);
    HmlValue _tmp75 = hml_val_i32(0);
    HmlValue _tmp73 = hml_both_i32(_tmp74, _tmp75) ? hml_i32_lt(_tmp74, _tmp75) : (hml_both_i64(_tmp74, _tmp75) ? hml_i64_lt(_tmp74, _tmp75) : hml_binary_op(HML_OP_LESS, _tmp74, _tmp75));
    hml_release_if_needed(&_tmp74);
    hml_release_if_needed(&_tmp75);
    HmlValue _tmp72;
    if (hml_to_bool(_tmp73)) {
        _tmp72 = hml_val_bool(1);
    } else {
        HmlValue _tmp78 = offset;
        hml_retain_if_needed(&_tmp78);
        HmlValue _tmp79 = hml_val_i32(4);
        HmlValue _tmp77 = hml_both_i32(_tmp78, _tmp79) ? hml_i32_add(_tmp78, _tmp79) : (hml_both_i64(_tmp78, _tmp79) ? hml_i64_add(_tmp78, _tmp79) : hml_binary_op(HML_OP_ADD, _tmp78, _tmp79));
        hml_release_if_needed(&_tmp78);
        hml_release_if_needed(&_tmp79);
        HmlValue _tmp80 = _size;
        hml_retain_if_needed(&_tmp80);
        HmlValue _tmp76 = hml_both_i32(_tmp77, _tmp80) ? hml_i32_gt(_tmp77, _tmp80) : (hml_both_i64(_tmp77, _tmp80) ? hml_i64_gt(_tmp77, _tmp80) : hml_binary_op(HML_OP_GREATER, _tmp77, _tmp80));
        hml_release_if_needed(&_tmp77);
        hml_release_if_needed(&_tmp80);
        _tmp72 = hml_val_bool(hml_to_bool(_tmp76));
        hml_release_if_needed(&_tmp76);
    }
    hml_release_if_needed(&_tmp73);
    int _tmp81 = hml_to_bool(_tmp72);
    hml_release(&_tmp72);
    if (_tmp81) {
        {
            HmlValue _tmp82 = hml_val_string("MappedFile.read_i32: offset out of bounds");
            hml_throw(_tmp82);
        }
    }
    HmlValue _tmp86 = hml_self;
    hml_retain_if_needed(&_tmp86);
    HmlValue _tmp85 = hml_object_get_field_required(_tmp86, "ptr");
    hml_release(&_tmp86);
    HmlValue _tmp87 = offset;
    hml_retain_if_needed(&_tmp87);
    HmlValue _tmp88 = hml_val_i32(1);
    HmlValue _tmp84 = hml_builtin_ptr_offset(NULL, _tmp85, _tmp87, _tmp88);
    hml_release(&_tmp85);
    hml_release(&_tmp87);
    hml_release(&_tmp88);
    HmlValue _tmp83 = hml_builtin_ptr_read_i32(NULL, _tmp84);
    hml_release(&_tmp84);
    HML_CALL_EXIT();
    return _tmp83;
    hml_release(&_size);
    HML_CALL_EXIT();
    return hml_val_null();
}

HmlValue hml_fn_anon_2(HmlClosureEnv *_closure_env, HmlValue offset) {
    HmlValue _size = hml_closure_env_get(_closure_env, 0);
    HML_CALL_ENTER();
    HmlValue _tmp91 = offset;
    hml_retain_if_needed(&_tmp91);
    HmlValue _tmp92 = hml_val_i32(0);
    HmlValue _tmp90 = hml_both_i32(_tmp91, _tmp92) ? hml_i32_lt(_tmp91, _tmp92) : (hml_both_i64(_tmp91, _tmp92) ? hml_i64_lt(_tmp91, _tmp92) : hml_binary_op(HML_OP_LESS, _tmp91, _tmp92));
    hml_release_if_needed(&_tmp91);
    hml_release_if_needed(&_tmp92);
    HmlValue _tmp89;
    if (hml_to_bool(_tmp90)) {
        _tmp89 = hml_val_bool(1);
    } else {
        HmlValue _tmp95 = offset;
        hml_retain_if_needed(&_tmp95);
        HmlValue _tmp96 = hml_val_i32(8);
        HmlValue _tmp94 = hml_both_i32(_tmp95, _tmp96) ? hml_i32_add(_tmp95, _tmp96) : (hml_both_i64(_tmp95, _tmp96) ? hml_i64_add(_tmp95, _tmp96) : hml_binary_op(HML_OP_ADD, _tmp95, _tmp96));
        hml_release_if_needed(&_tmp95);
        hml_release_if_needed(&_tmp96);
        HmlValue _tmp97 = _size;
        hml_retain_if_needed(&_tmp97);
        HmlValue _tmp93 = hml_both_i32(_tmp94, _tmp97) ? hml_i32_gt(_tmp94, _tmp97) : (hml_both_i64(_tmp94, _tmp97) ? hml_i64_gt(_tmp94, _tmp97) : hml_binary_op(HML_OP_GREATER, _tmp94, _tmp97));
        hml_release_if_needed(&_tmp94);
        hml_release_if_needed(&_tmp97);
        _tmp89 = hml_val_bool(hml_to_bool(_tmp93));
        hml_release_if_needed(&_tmp93);
    }
    hml_release_if_needed(&_tmp90);
    int _tmp98 = hml_to_bool(_tmp89);
    hml_release(&_tmp89);
    if (_tmp98) {
        {
            HmlValue _tmp99 = hml_val_string("MappedFile.read_i64: offset out of bounds");
            hml_throw(_tmp99);
        }
    }
    HmlValue _tmp103 = hml_self;
    hml_retain_if_needed(&_tmp103);
    HmlValue _tmp102 = hml_object_get_field_required(_tmp103, "ptr");
    hml_release(&_tmp103);
    HmlValue _tmp104 = offset;
    hml_retain_if_needed(&_tmp104);
    HmlValue _tmp105 = hml_val_i32(1);
    HmlValue _tmp101 = hml_builtin_ptr_offset(NULL, _tmp102, _tmp104, _tmp105);
    hml_release(&_tmp102);
    hml_release(&_tmp104);
    hml_release(&_tmp105);
    HmlValue _tmp100 = hml_builtin_ptr_read_i64(NULL, _tmp101);
    hml_release(&_tmp101);
    HML_CALL_EXIT();
    return _tmp100;
    hml_release(&_size);
    HML_CALL_EXIT();
    return hml_val_null();
}

HmlValue hml_fn_anon_3(HmlClosureEnv *_closure_env, HmlValue offset) {
    HmlValue _size = hml_closure_env_get(_closure_env, 0);
    HML_CALL_ENTER();
    HmlValue _tmp108 = offset;
    hml_retain_if_needed(&_tmp108);
    HmlValue _tmp109 = hml_val_i32(0);
    HmlValue _tmp107 = hml_both_i32(_tmp108, _tmp109) ? hml_i32_lt(_tmp108, _tmp109) : (hml_both_i64(_tmp108, _tmp109) ? hml_i64_lt(_tmp108, _tmp109) : hml_binary_op(HML_OP_LESS, _tmp108, _tmp109));
    hml_release_if_needed(&_tmp108);
    hml_release_if_needed(&_tmp109);
    HmlValue _tmp106;
    if (hml_to_bool(_tmp107)) {
        _tmp106 = hml_val_bool(1);
    } else {
        HmlValue _tmp112 = offset;
        hml_retain_if_needed(&_tmp112);
        HmlValue _tmp113 = hml_val_i32(8);
        HmlValue _tmp111 = hml_both_i32(_tmp112, _tmp113) ? hml_i32_add(_tmp112, _tmp113) : (hml_both_i64(_tmp112, _tmp113) ? hml_i64_add(_tmp112, _tmp113) : hml_binary_op(HML_OP_ADD, _tmp112, _tmp113));
        hml_release_if_needed(&_tmp112);
        hml_release_if_needed(&_tmp113);
        HmlValue _tmp114 = _size;
        hml_retain_if_needed(&_tmp114);
        HmlValue _tmp110 = hml_both_i32(_tmp111, _tmp114) ? hml_i32_gt(_tmp111, _tmp114) : (hml_both_i64(_tmp111, _tmp114) ? hml_i64_gt(_tmp111, _tmp114) : hml_binary_op(HML_OP_GREATER, _tmp111, _tmp114));
        hml_release_if_needed(&_tmp111);
        hml_release_if_needed(&_tmp114);
        _tmp106 = hml_val_bool(hml_to_bool(_tmp110));
        hml_release_if_needed(&_tmp110);
    }
    hml_release_if_needed(&_tmp107);
    int _tmp115 = hml_to_bool(_tmp106);
    hml_release(&_tmp106);
    if (_tmp115) {
        {
            HmlValue _tmp116 = hml_val_string("MappedFile.read_f64: offset out of bounds");
            hml_throw(_tmp116);
        }
    }
    HmlValue _tmp120 = hml_self;
    hml_retain_if_needed(&_tmp120);
    HmlValue _tmp119 = hml_object_get_field_required(_tmp120, "ptr");
    hml_release(&_tmp120);
    HmlValue _tmp121 = offset;
    hml_retain_if_needed(&_tmp121);
    HmlValue _tmp122 = hml_val_i32(1);
    HmlValue _tmp118 = hml_builtin_ptr_offset(NULL, _tmp119, _tmp121, _tmp122);
    hml_release(&_tmp119);
    hml_release(&_tmp121);
    hml_release(&_tmp122);
    HmlValue _tmp117 = hml_builtin_ptr_read_f64(NULL, _tmp118);
    hml_release(&_tmp118);
    HML_CALL_EXIT();
    return _tmp117;
    hml_release(&_size);
    HML_CALL_EXIT();
    return hml_val_null();
}

HmlValue hml_fn_anon_4(HmlClosureEnv *_closure_env, HmlValue offset, HmlValue val) {
    HmlValue _v__mode = hml_closure_env_get(_closure_env, 7);
    HmlValue _size = hml_closure_env_get(_closure_env, 0);
    HML_CALL_ENTER();
    HmlValue _tmp124 = _v__mode;
    hml_retain_if_needed(&_tmp124);
    HmlValue _tmp125 = hml_val_string("rw");
    HmlValue _tmp123 = hml_both_i32(_tmp124, _tmp125) ? hml_i32_ne(_tmp124, _tmp125) : (hml_both_i64(_tmp124, _tmp125) ? hml_i64_ne(_tmp124, _tmp125) : hml_binary_op(HML_OP_NOT_EQUAL, _tmp124, _tmp125));
    hml_release_if_needed(&_tmp124);
    hml_release_if_needed(&_tmp125);
    int _tmp126 = hml_to_bool(_tmp123);
    hml_release(&_tmp123);
    if (_tmp126) {
        {
            HmlValue _tmp127 = hml_val_string("MappedFile.write_u8: file not opened in rw mode");
            hml_throw(_tmp127);
        }
    }
    HmlValue _tmp130 = offset;
    hml_retain_if_needed(&_tmp130);
    HmlValue _tmp131 = hml_val_i32(0);
    HmlValue _tmp129 = hml_both_i32(_tmp130, _tmp131) ? hml_i32_lt(_tmp130, _tmp131) : (hml_both_i64(_tmp130, _tmp131) ? hml_i64_lt(_tmp130, _tmp131) : hml_binary_op(HML_OP_LESS, _tmp130, _tmp131));
    hml_release_if_needed(&_tmp130);
    hml_release_if_needed(&_tmp131);
    HmlValue _tmp128;
    if (hml_to_bool(_tmp129)) {
        _tmp128 = hml_val_bool(1);
    } else {
        HmlValue _tmp133 = offset;
        hml_retain_if_needed(&_tmp133);
        HmlValue _tmp134 = _size;
        hml_retain_if_needed(&_tmp134);
        HmlValue _tmp132 = hml_both_i32(_tmp133, _tmp134) ? hml_i32_ge(_tmp133, _tmp134) : (hml_both_i64(_tmp133, _tmp134) ? hml_i64_ge(_tmp133, _tmp134) : hml_binary_op(HML_OP_GREATER_EQUAL, _tmp133, _tmp134));
        hml_release_if_needed(&_tmp133);
        hml_release_if_needed(&_tmp134);
        _tmp128 = hml_val_bool(hml_to_bool(_tmp132));
        hml_release_if_needed(&_tmp132);
    }
    hml_release_if_needed(&_tmp129);
    int _tmp135 = hml_to_bool(_tmp128);
    hml_release(&_tmp128);
    if (_tmp135) {
        {
            HmlValue _tmp136 = hml_val_string("MappedFile.write_u8: offset out of bounds");
            hml_throw(_tmp136);
        }
    }
    HmlValue _tmp140 = hml_self;
    hml_retain_if_needed(&_tmp140);
    HmlValue _tmp139 = hml_object_get_field_required(_tmp140, "ptr");
    hml_release(&_tmp140);
    HmlValue _tmp141 = offset;
    hml_retain_if_needed(&_tmp141);
    HmlValue _tmp142 = hml_val_i32(1);
    HmlValue _tmp138 = hml_builtin_ptr_offset(NULL, _tmp139, _tmp141, _tmp142);
    hml_release(&_tmp139);
    hml_release(&_tmp141);
    hml_release(&_tmp142);
    HmlValue _tmp143 = val;
    hml_retain_if_needed(&_tmp143);
    HmlValue _tmp137 = hml_builtin_ptr_write_u8(NULL, _tmp138, _tmp143);
    hml_release(&_tmp138);
    hml_release(&_tmp143);
    hml_release(&_tmp137);
    hml_release(&_v__mode);
    hml_release(&_size);
    HML_CALL_EXIT();
    return hml_val_null();
}

HmlValue hml_fn_anon_5(HmlClosureEnv *_closure_env, HmlValue offset, HmlValue val) {
    HmlValue _v__mode = hml_closure_env_get(_closure_env, 7);
    HmlValue _size = hml_closure_env_get(_closure_env, 0);
    HML_CALL_ENTER();
    HmlValue _tmp145 = _v__mode;
    hml_retain_if_needed(&_tmp145);
    HmlValue _tmp146 = hml_val_string("rw");
    HmlValue _tmp144 = hml_both_i32(_tmp145, _tmp146) ? hml_i32_ne(_tmp145, _tmp146) : (hml_both_i64(_tmp145, _tmp146) ? hml_i64_ne(_tmp145, _tmp146) : hml_binary_op(HML_OP_NOT_EQUAL, _tmp145, _tmp146));
    hml_release_if_needed(&_tmp145);
    hml_release_if_needed(&_tmp146);
    int _tmp147 = hml_to_bool(_tmp144);
    hml_release(&_tmp144);
    if (_tmp147) {
        {
            HmlValue _tmp148 = hml_val_string("MappedFile.write_i32: file not opened in rw mode");
            hml_throw(_tmp148);
        }
    }
    HmlValue _tmp151 = offset;
    hml_retain_if_needed(&_tmp151);
    HmlValue _tmp152 = hml_val_i32(0);
    HmlValue _tmp150 = hml_both_i32(_tmp151, _tmp152) ? hml_i32_lt(_tmp151, _tmp152) : (hml_both_i64(_tmp151, _tmp152) ? hml_i64_lt(_tmp151, _tmp152) : hml_binary_op(HML_OP_LESS, _tmp151, _tmp152));
    hml_release_if_needed(&_tmp151);
    hml_release_if_needed(&_tmp152);
    HmlValue _tmp149;
    if (hml_to_bool(_tmp150)) {
        _tmp149 = hml_val_bool(1);
    } else {
        HmlValue _tmp155 = offset;
        hml_retain_if_needed(&_tmp155);
        HmlValue _tmp156 = hml_val_i32(4);
        HmlValue _tmp154 = hml_both_i32(_tmp155, _tmp156) ? hml_i32_add(_tmp155, _tmp156) : (hml_both_i64(_tmp155, _tmp156) ? hml_i64_add(_tmp155, _tmp156) : hml_binary_op(HML_OP_ADD, _tmp155, _tmp156));
        hml_release_if_needed(&_tmp155);
        hml_release_if_needed(&_tmp156);
        HmlValue _tmp157 = _size;
        hml_retain_if_needed(&_tmp157);
        HmlValue _tmp153 = hml_both_i32(_tmp154, _tmp157) ? hml_i32_gt(_tmp154, _tmp157) : (hml_both_i64(_tmp154, _tmp157) ? hml_i64_gt(_tmp154, _tmp157) : hml_binary_op(HML_OP_GREATER, _tmp154, _tmp157));
        hml_release_if_needed(&_tmp154);
        hml_release_if_needed(&_tmp157);
        _tmp149 = hml_val_bool(hml_to_bool(_tmp153));
        hml_release_if_needed(&_tmp153);
    }
    hml_release_if_needed(&_tmp150);
    int _tmp158 = hml_to_bool(_tmp149);
    hml_release(&_tmp149);
    if (_tmp158) {
        {
            HmlValue _tmp159 = hml_val_string("MappedFile.write_i32: offset out of bounds");
            hml_throw(_tmp159);
        }
    }
    HmlValue _tmp163 = hml_self;
    hml_retain_if_needed(&_tmp163);
    HmlValue _tmp162 = hml_object_get_field_required(_tmp163, "ptr");
    hml_release(&_tmp163);
    HmlValue _tmp164 = offset;
    hml_retain_if_needed(&_tmp164);
    HmlValue _tmp165 = hml_val_i32(1);
    HmlValue _tmp161 = hml_builtin_ptr_offset(NULL, _tmp162, _tmp164, _tmp165);
    hml_release(&_tmp162);
    hml_release(&_tmp164);
    hml_release(&_tmp165);
    HmlValue _tmp166 = val;
    hml_retain_if_needed(&_tmp166);
    HmlValue _tmp160 = hml_builtin_ptr_write_i32(NULL, _tmp161, _tmp166);
    hml_release(&_tmp161);
    hml_release(&_tmp166);
    hml_release(&_tmp160);
    hml_release(&_v__mode);
    hml_release(&_size);
    HML_CALL_EXIT();
    return hml_val_null();
}

HmlValue hml_fn_anon_6(HmlClosureEnv *_closure_env) {
    HML_CALL_ENTER();
    HmlValue _tmp168 = _main_mmap_sync;
    hml_retain_if_needed(&_tmp168);
    HmlValue _tmp171 = hml_self;
    hml_retain_if_needed(&_tmp171);
    HmlValue _tmp170 = hml_object_get_field_required(_tmp171, "ptr");
    hml_release(&_tmp171);
    HmlValue _args169[1];
    _args169[0] = _tmp170;
    HmlValue _tmp167 = hml_call_function(_tmp168, _args169, 1);
    hml_release(&_tmp170);
    hml_release(&_tmp168);
    HML_CALL_EXIT();
    return _tmp167;
    HML_CALL_EXIT();
    return hml_val_null();
}

HmlValue hml_fn_anon_7(HmlClosureEnv *_closure_env, HmlValue advice) {
    HML_CALL_ENTER();
    HmlValue _tmp173 = _main_mmap_advise;
    hml_retain_if_needed(&_tmp173);
    HmlValue _tmp176 = hml_self;
    hml_retain_if_needed(&_tmp176);
    HmlValue _tmp175 = hml_object_get_field_required(_tmp176, "ptr");
    hml_release(&_tmp176);
    HmlValue _tmp177 = advice;
    hml_retain_if_needed(&_tmp177);
    HmlValue _args174[2];
    _args174[0] = _tmp175;
    _args174[1] = _tmp177;
    HmlValue _tmp172 = hml_call_function(_tmp173, _args174, 2);
    hml_release(&_tmp175);
    hml_release(&_tmp177);
    hml_release(&_tmp173);
    HML_CALL_EXIT();
    return _tmp172;
    HML_CALL_EXIT();
    return hml_val_null();
}

HmlValue hml_fn_anon_8(HmlClosureEnv *_closure_env) {
    HML_CALL_ENTER();
    HmlValue _tmp179 = _main_mmap_close;
    hml_retain_if_needed(&_tmp179);
    HmlValue _tmp182 = hml_self;
    hml_retain_if_needed(&_tmp182);
    HmlValue _tmp181 = hml_object_get_field_required(_tmp182, "ptr");
    hml_release(&_tmp182);
    HmlValue _args180[1];
    _args180[0] = _tmp181;
    HmlValue _tmp178 = hml_call_function(_tmp179, _args180, 1);
    hml_release(&_tmp181);
    hml_release(&_tmp179);
    HML_CALL_EXIT();
    return _tmp178;
    HML_CALL_EXIT();
    return hml_val_null();
}

HmlValue hml_fn_anon_9(HmlClosureEnv *_closure_env, HmlValue path, HmlValue mode) {
    if (mode.type == HML_VAL_NULL) {
        HmlValue _tmp183 = hml_val_string("r");
        mode = _tmp183;
    }
    HML_CALL_ENTER();
    HmlClosureEnv *_shared_env_184 = hml_closure_env_new(13);
    HmlValue _tmp186 = _main_mmap_open;
    hml_retain_if_needed(&_tmp186);
    HmlValue _tmp188 = path;
    hml_retain_if_needed(&_tmp188);
    HmlValue _tmp189 = mode;
    hml_retain_if_needed(&_tmp189);
    HmlValue _args187[2];
    _args187[0] = _tmp188;
    _args187[1] = _tmp189;
    HmlValue _tmp185 = hml_call_function(_tmp186, _args187, 2);
    hml_release(&_tmp188);
    hml_release(&_tmp189);
    hml_release(&_tmp186);
    HmlValue _ptr = _tmp185;
    HmlValue _tmp191 = _ptr;
    hml_retain_if_needed(&_tmp191);
    HmlValue _tmp192 = hml_val_null();
    HmlValue _tmp190 = hml_both_i32(_tmp191, _tmp192) ? hml_i32_eq(_tmp191, _tmp192) : (hml_both_i64(_tmp191, _tmp192) ? hml_i64_eq(_tmp191, _tmp192) : hml_binary_op(HML_OP_EQUAL, _tmp191, _tmp192));
    hml_release_if_needed(&_tmp191);
    hml_release_if_needed(&_tmp192);
    int _tmp193 = hml_to_bool(_tmp190);
    hml_release(&_tmp190);
    if (_tmp193) {
        {
            HmlValue _tmp195 = hml_val_string("MappedFile: failed to map '");
            HmlValue _tmp196 = path;
            hml_retain_if_needed(&_tmp196);
            HmlValue _tmp197 = hml_val_string("'");
            HmlValue _tmp194 = hml_string_concat3(_tmp195, _tmp196, _tmp197);
            hml_release_if_needed(&_tmp195);
            hml_release_if_needed(&_tmp196);
            hml_release_if_needed(&_tmp197);
            hml_throw(_tmp194);
        }
    }
    HmlValue _tmp199 = _main_mmap_size;
    hml_retain_if_needed(&_tmp199);
    HmlValue _tmp201 = _ptr;
    hml_retain_if_needed(&_tmp201);
    HmlValue _args200[1];
    _args200[0] = _tmp201;
    HmlValue _tmp198 = hml_call_function(_tmp199, _args200, 1);
    hml_release(&_tmp201);
    hml_release(&_tmp199);
    HmlValue _size = _tmp198;
    HmlValue _tmp202 = mode;
    hml_retain_if_needed(&_tmp202);
    HmlValue _v__mode = _tmp202;
    HmlValue _tmp203 = hml_val_object();
    HmlValue _tmp204 = _ptr;
    hml_retain_if_needed(&_tmp204);
    hml_object_set_field(_tmp203, "ptr", _tmp204);
    hml_release(&_tmp204);
    HmlValue _tmp205 = _size;
    hml_retain_if_needed(&_tmp205);
    hml_object_set_field(_tmp203, "size", _tmp205);
    hml_release(&_tmp205);
    hml_closure_env_set(_shared_env_184, 0, _size);
    hml_closure_env_retain(_shared_env_184);
    HmlValue _tmp206 = hml_val_function_with_env_rest((void*)hml_fn_anon_10, (void*)_shared_env_184, 1, 1, 0, 0);
    const char *_param_names207[1] = {
"offset"    };
    hml_function_set_param_names(_tmp206, _param_names207, 1);
    hml_object_set_field(_tmp203, "read_u8", _tmp206);
    hml_release(&_tmp206);
    hml_closure_env_set(_shared_env_184, 0, _size);
    hml_closure_env_retain(_shared_env_184);
    HmlValue _tmp208 = hml_val_function_with_env_rest((void*)hml_fn_anon_11, (void*)_shared_env_184, 1, 1, 0, 0);
    const char *_param_names209[1] = {
"offset"    };
    hml_function_set_param_names(_tmp208, _param_names209, 1);
    hml_object_set_field(_tmp203, "read_i32", _tmp208);
    hml_release(&_tmp208);
    hml_closure_env_set(_shared_env_184, 0, _size);
    hml_closure_env_retain(_shared_env_184);
    HmlValue _tmp210 = hml_val_function_with_env_rest((void*)hml_fn_anon_12, (void*)_shared_env_184, 1, 1, 0, 0);
    const char *_param_names211[1] = {
"offset"    };
    hml_function_set_param_names(_tmp210, _param_names211, 1);
    hml_object_set_field(_tmp203, "read_i64", _tmp210);
    hml_release(&_tmp210);
    hml_closure_env_set(_shared_env_184, 0, _size);
    hml_closure_env_retain(_shared_env_184);
    HmlValue _tmp212 = hml_val_function_with_env_rest((void*)hml_fn_anon_13, (void*)_shared_env_184, 1, 1, 0, 0);
    const char *_param_names213[1] = {
"offset"    };
    hml_function_set_param_names(_tmp212, _param_names213, 1);
    hml_object_set_field(_tmp203, "read_f64", _tmp212);
    hml_release(&_tmp212);
    hml_closure_env_set(_shared_env_184, 7, _v__mode);
    hml_closure_env_set(_shared_env_184, 0, _size);
    hml_closure_env_retain(_shared_env_184);
    HmlValue _tmp214 = hml_val_function_with_env_rest((void*)hml_fn_anon_14, (void*)_shared_env_184, 2, 2, 0, 0);
    const char *_param_names215[2] = {
"offset", "val"    };
    hml_function_set_param_names(_tmp214, _param_names215, 2);
    hml_object_set_field(_tmp203, "write_u8", _tmp214);
    hml_release(&_tmp214);
    hml_closure_env_set(_shared_env_184, 7, _v__mode);
    hml_closure_env_set(_shared_env_184, 0, _size);
    hml_closure_env_retain(_shared_env_184);
    HmlValue _tmp216 = hml_val_function_with_env_rest((void*)hml_fn_anon_15, (void*)_shared_env_184, 2, 2, 0, 0);
    const char *_param_names217[2] = {
"offset", "val"    };
    hml_function_set_param_names(_tmp216, _param_names217, 2);
    hml_object_set_field(_tmp203, "write_i32", _tmp216);
    hml_release(&_tmp216);
    HmlValue _tmp218 = hml_val_function_rest((void*)hml_fn_anon_16, 0, 0, 0, 0);
    hml_object_set_field(_tmp203, "sync", _tmp218);
    hml_release(&_tmp218);
    HmlValue _tmp219 = hml_val_function_rest((void*)hml_fn_anon_17, 1, 1, 0, 0);
    const char *_param_names220[1] = {
"advice"    };
    hml_function_set_param_names(_tmp219, _param_names220, 1);
    hml_object_set_field(_tmp203, "advise", _tmp219);
    hml_release(&_tmp219);
    HmlValue _tmp221 = hml_val_function_rest((void*)hml_fn_anon_18, 0, 0, 0, 0);
    hml_object_set_field(_tmp203, "close", _tmp221);
    hml_release(&_tmp221);
    hml_release(&_ptr);
    hml_release(&_size);
    hml_release(&_v__mode);
    hml_closure_env_release(_shared_env_184);
    HML_CALL_EXIT();
    return _tmp203;
    hml_release(&_ptr);
    hml_release(&_size);
    hml_release(&_v__mode);
    hml_closure_env_release(_shared_env_184);
    HML_CALL_EXIT();
    return hml_val_null();
}

HmlValue hml_fn_anon_10(HmlClosureEnv *_closure_env, HmlValue offset) {
    HmlValue _size = hml_closure_env_get(_closure_env, 0);
    HML_CALL_ENTER();
    HmlValue _tmp224 = offset;
    hml_retain_if_needed(&_tmp224);
    HmlValue _tmp225 = hml_val_i32(0);
    HmlValue _tmp223 = hml_both_i32(_tmp224, _tmp225) ? hml_i32_lt(_tmp224, _tmp225) : (hml_both_i64(_tmp224, _tmp225) ? hml_i64_lt(_tmp224, _tmp225) : hml_binary_op(HML_OP_LESS, _tmp224, _tmp225));
    hml_release_if_needed(&_tmp224);
    hml_release_if_needed(&_tmp225);
    HmlValue _tmp222;
    if (hml_to_bool(_tmp223)) {
        _tmp222 = hml_val_bool(1);
    } else {
        HmlValue _tmp227 = offset;
        hml_retain_if_needed(&_tmp227);
        HmlValue _tmp228 = _size;
        hml_retain_if_needed(&_tmp228);
        HmlValue _tmp226 = hml_both_i32(_tmp227, _tmp228) ? hml_i32_ge(_tmp227, _tmp228) : (hml_both_i64(_tmp227, _tmp228) ? hml_i64_ge(_tmp227, _tmp228) : hml_binary_op(HML_OP_GREATER_EQUAL, _tmp227, _tmp228));
        hml_release_if_needed(&_tmp227);
        hml_release_if_needed(&_tmp228);
        _tmp222 = hml_val_bool(hml_to_bool(_tmp226));
        hml_release_if_needed(&_tmp226);
    }
    hml_release_if_needed(&_tmp223);
    int _tmp229 = hml_to_bool(_tmp222);
    hml_release(&_tmp222);
    if (_tmp229) {
        {
            HmlValue _tmp230 = hml_val_string("MappedFile.read_u8: offset out of bounds");
            hml_throw(_tmp230);
        }
    }
    HmlValue _tmp234 = hml_self;
    hml_retain_if_needed(&_tmp234);
    HmlValue _tmp233 = hml_object_get_field_required(_tmp234, "ptr");
    hml_release(&_tmp234);
    HmlValue _tmp235 = offset;
    hml_retain_if_needed(&_tmp235);
    HmlValue _tmp236 = hml_val_i32(1);
    HmlValue _tmp232 = hml_builtin_ptr_offset(NULL, _tmp233, _tmp235, _tmp236);
    hml_release(&_tmp233);
    hml_release(&_tmp235);
    hml_release(&_tmp236);
    HmlValue _tmp231 = hml_builtin_ptr_read_u8(NULL, _tmp232);
    hml_release(&_tmp232);
    HML_CALL_EXIT();
    return _tmp231;
    hml_release(&_size);
    HML_CALL_EXIT();
    return hml_val_null();
}

HmlValue hml_fn_anon_11(HmlClosureEnv *_closure_env, HmlValue offset) {
    HmlValue _size = hml_closure_env_get(_closure_env, 0);
    HML_CALL_ENTER();
    HmlValue _tmp239 = offset;
    hml_retain_if_needed(&_tmp239);
    HmlValue _tmp240 = hml_val_i32(0);
    HmlValue _tmp238 = hml_both_i32(_tmp239, _tmp240) ? hml_i32_lt(_tmp239, _tmp240) : (hml_both_i64(_tmp239, _tmp240) ? hml_i64_lt(_tmp239, _tmp240) : hml_binary_op(HML_OP_LESS, _tmp239, _tmp240));
    hml_release_if_needed(&_tmp239);
    hml_release_if_needed(&_tmp240);
    HmlValue _tmp237;
    if (hml_to_bool(_tmp238)) {
        _tmp237 = hml_val_bool(1);
    } else {
        HmlValue _tmp243 = offset;
        hml_retain_if_needed(&_tmp243);
        HmlValue _tmp244 = hml_val_i32(4);
        HmlValue _tmp242 = hml_both_i32(_tmp243, _tmp244) ? hml_i32_add(_tmp243, _tmp244) : (hml_both_i64(_tmp243, _tmp244) ? hml_i64_add(_tmp243, _tmp244) : hml_binary_op(HML_OP_ADD, _tmp243, _tmp244));
        hml_release_if_needed(&_tmp243);
        hml_release_if_needed(&_tmp244);
        HmlValue _tmp245 = _size;
        hml_retain_if_needed(&_tmp245);
        HmlValue _tmp241 = hml_both_i32(_tmp242, _tmp245) ? hml_i32_gt(_tmp242, _tmp245) : (hml_both_i64(_tmp242, _tmp245) ? hml_i64_gt(_tmp242, _tmp245) : hml_binary_op(HML_OP_GREATER, _tmp242, _tmp245));
        hml_release_if_needed(&_tmp242);
        hml_release_if_needed(&_tmp245);
        _tmp237 = hml_val_bool(hml_to_bool(_tmp241));
        hml_release_if_needed(&_tmp241);
    }
    hml_release_if_needed(&_tmp238);
    int _tmp246 = hml_to_bool(_tmp237);
    hml_release(&_tmp237);
    if (_tmp246) {
        {
            HmlValue _tmp247 = hml_val_string("MappedFile.read_i32: offset out of bounds");
            hml_throw(_tmp247);
        }
    }
    HmlValue _tmp251 = hml_self;
    hml_retain_if_needed(&_tmp251);
    HmlValue _tmp250 = hml_object_get_field_required(_tmp251, "ptr");
    hml_release(&_tmp251);
    HmlValue _tmp252 = offset;
    hml_retain_if_needed(&_tmp252);
    HmlValue _tmp253 = hml_val_i32(1);
    HmlValue _tmp249 = hml_builtin_ptr_offset(NULL, _tmp250, _tmp252, _tmp253);
    hml_release(&_tmp250);
    hml_release(&_tmp252);
    hml_release(&_tmp253);
    HmlValue _tmp248 = hml_builtin_ptr_read_i32(NULL, _tmp249);
    hml_release(&_tmp249);
    HML_CALL_EXIT();
    return _tmp248;
    hml_release(&_size);
    HML_CALL_EXIT();
    return hml_val_null();
}

HmlValue hml_fn_anon_12(HmlClosureEnv *_closure_env, HmlValue offset) {
    HmlValue _size = hml_closure_env_get(_closure_env, 0);
    HML_CALL_ENTER();
    HmlValue _tmp256 = offset;
    hml_retain_if_needed(&_tmp256);
    HmlValue _tmp257 = hml_val_i32(0);
    HmlValue _tmp255 = hml_both_i32(_tmp256, _tmp257) ? hml_i32_lt(_tmp256, _tmp257) : (hml_both_i64(_tmp256, _tmp257) ? hml_i64_lt(_tmp256, _tmp257) : hml_binary_op(HML_OP_LESS, _tmp256, _tmp257));
    hml_release_if_needed(&_tmp256);
    hml_release_if_needed(&_tmp257);
    HmlValue _tmp254;
    if (hml_to_bool(_tmp255)) {
        _tmp254 = hml_val_bool(1);
    } else {
        HmlValue _tmp260 = offset;
        hml_retain_if_needed(&_tmp260);
        HmlValue _tmp261 = hml_val_i32(8);
        HmlValue _tmp259 = hml_both_i32(_tmp260, _tmp261) ? hml_i32_add(_tmp260, _tmp261) : (hml_both_i64(_tmp260, _tmp261) ? hml_i64_add(_tmp260, _tmp261) : hml_binary_op(HML_OP_ADD, _tmp260, _tmp261));
        hml_release_if_needed(&_tmp260);
        hml_release_if_needed(&_tmp261);
        HmlValue _tmp262 = _size;
        hml_retain_if_needed(&_tmp262);
        HmlValue _tmp258 = hml_both_i32(_tmp259, _tmp262) ? hml_i32_gt(_tmp259, _tmp262) : (hml_both_i64(_tmp259, _tmp262) ? hml_i64_gt(_tmp259, _tmp262) : hml_binary_op(HML_OP_GREATER, _tmp259, _tmp262));
        hml_release_if_needed(&_tmp259);
        hml_release_if_needed(&_tmp262);
        _tmp254 = hml_val_bool(hml_to_bool(_tmp258));
        hml_release_if_needed(&_tmp258);
    }
    hml_release_if_needed(&_tmp255);
    int _tmp263 = hml_to_bool(_tmp254);
    hml_release(&_tmp254);
    if (_tmp263) {
        {
            HmlValue _tmp264 = hml_val_string("MappedFile.read_i64: offset out of bounds");
            hml_throw(_tmp264);
        }
    }
    HmlValue _tmp268 = hml_self;
    hml_retain_if_needed(&_tmp268);
    HmlValue _tmp267 = hml_object_get_field_required(_tmp268, "ptr");
    hml_release(&_tmp268);
    HmlValue _tmp269 = offset;
    hml_retain_if_needed(&_tmp269);
    HmlValue _tmp270 = hml_val_i32(1);
    HmlValue _tmp266 = hml_builtin_ptr_offset(NULL, _tmp267, _tmp269, _tmp270);
    hml_release(&_tmp267);
    hml_release(&_tmp269);
    hml_release(&_tmp270);
    HmlValue _tmp265 = hml_builtin_ptr_read_i64(NULL, _tmp266);
    hml_release(&_tmp266);
    HML_CALL_EXIT();
    return _tmp265;
    hml_release(&_size);
    HML_CALL_EXIT();
    return hml_val_null();
}

HmlValue hml_fn_anon_13(HmlClosureEnv *_closure_env, HmlValue offset) {
    HmlValue _size = hml_closure_env_get(_closure_env, 0);
    HML_CALL_ENTER();
    HmlValue _tmp273 = offset;
    hml_retain_if_needed(&_tmp273);
    HmlValue _tmp274 = hml_val_i32(0);
    HmlValue _tmp272 = hml_both_i32(_tmp273, _tmp274) ? hml_i32_lt(_tmp273, _tmp274) : (hml_both_i64(_tmp273, _tmp274) ? hml_i64_lt(_tmp273, _tmp274) : hml_binary_op(HML_OP_LESS, _tmp273, _tmp274));
    hml_release_if_needed(&_tmp273);
    hml_release_if_needed(&_tmp274);
    HmlValue _tmp271;
    if (hml_to_bool(_tmp272)) {
        _tmp271 = hml_val_bool(1);
    } else {
        HmlValue _tmp277 = offset;
        hml_retain_if_needed(&_tmp277);
        HmlValue _tmp278 = hml_val_i32(8);
        HmlValue _tmp276 = hml_both_i32(_tmp277, _tmp278) ? hml_i32_add(_tmp277, _tmp278) : (hml_both_i64(_tmp277, _tmp278) ? hml_i64_add(_tmp277, _tmp278) : hml_binary_op(HML_OP_ADD, _tmp277, _tmp278));
        hml_release_if_needed(&_tmp277);
        hml_release_if_needed(&_tmp278);
        HmlValue _tmp279 = _size;
        hml_retain_if_needed(&_tmp279);
        HmlValue _tmp275 = hml_both_i32(_tmp276, _tmp279) ? hml_i32_gt(_tmp276, _tmp279) : (hml_both_i64(_tmp276, _tmp279) ? hml_i64_gt(_tmp276, _tmp279) : hml_binary_op(HML_OP_GREATER, _tmp276, _tmp279));
        hml_release_if_needed(&_tmp276);
        hml_release_if_needed(&_tmp279);
        _tmp271 = hml_val_bool(hml_to_bool(_tmp275));
        hml_release_if_needed(&_tmp275);
    }
    hml_release_if_needed(&_tmp272);
    int _tmp280 = hml_to_bool(_tmp271);
    hml_release(&_tmp271);
    if (_tmp280) {
        {
            HmlValue _tmp281 = hml_val_string("MappedFile.read_f64: offset out of bounds");
            hml_throw(_tmp281);
        }
    }
    HmlValue _tmp285 = hml_self;
    hml_retain_if_needed(&_tmp285);
    HmlValue _tmp284 = hml_object_get_field_required(_tmp285, "ptr");
    hml_release(&_tmp285);
    HmlValue _tmp286 = offset;
    hml_retain_if_needed(&_tmp286);
    HmlValue _tmp287 = hml_val_i32(1);
    HmlValue _tmp283 = hml_builtin_ptr_offset(NULL, _tmp284, _tmp286, _tmp287);
    hml_release(&_tmp284);
    hml_release(&_tmp286);
    hml_release(&_tmp287);
    HmlValue _tmp282 = hml_builtin_ptr_read_f64(NULL, _tmp283);
    hml_release(&_tmp283);
    HML_CALL_EXIT();
    return _tmp282;
    hml_release(&_size);
    HML_CALL_EXIT();
    return hml_val_null();
}

HmlValue hml_fn_anon_14(HmlClosureEnv *_closure_env, HmlValue offset, HmlValue val) {
    HmlValue _v__mode = hml_closure_env_get(_closure_env, 7);
    HmlValue _size = hml_closure_env_get(_closure_env, 0);
    HML_CALL_ENTER();
    HmlValue _tmp289 = _v__mode;
    hml_retain_if_needed(&_tmp289);
    HmlValue _tmp290 = hml_val_string("rw");
    HmlValue _tmp288 = hml_both_i32(_tmp289, _tmp290) ? hml_i32_ne(_tmp289, _tmp290) : (hml_both_i64(_tmp289, _tmp290) ? hml_i64_ne(_tmp289, _tmp290) : hml_binary_op(HML_OP_NOT_EQUAL, _tmp289, _tmp290));
    hml_release_if_needed(&_tmp289);
    hml_release_if_needed(&_tmp290);
    int _tmp291 = hml_to_bool(_tmp288);
    hml_release(&_tmp288);
    if (_tmp291) {
        {
            HmlValue _tmp292 = hml_val_string("MappedFile.write_u8: file not opened in rw mode");
            hml_throw(_tmp292);
        }
    }
    HmlValue _tmp295 = offset;
    hml_retain_if_needed(&_tmp295);
    HmlValue _tmp296 = hml_val_i32(0);
    HmlValue _tmp294 = hml_both_i32(_tmp295, _tmp296) ? hml_i32_lt(_tmp295, _tmp296) : (hml_both_i64(_tmp295, _tmp296) ? hml_i64_lt(_tmp295, _tmp296) : hml_binary_op(HML_OP_LESS, _tmp295, _tmp296));
    hml_release_if_needed(&_tmp295);
    hml_release_if_needed(&_tmp296);
    HmlValue _tmp293;
    if (hml_to_bool(_tmp294)) {
        _tmp293 = hml_val_bool(1);
    } else {
        HmlValue _tmp298 = offset;
        hml_retain_if_needed(&_tmp298);
        HmlValue _tmp299 = _size;
        hml_retain_if_needed(&_tmp299);
        HmlValue _tmp297 = hml_both_i32(_tmp298, _tmp299) ? hml_i32_ge(_tmp298, _tmp299) : (hml_both_i64(_tmp298, _tmp299) ? hml_i64_ge(_tmp298, _tmp299) : hml_binary_op(HML_OP_GREATER_EQUAL, _tmp298, _tmp299));
        hml_release_if_needed(&_tmp298);
        hml_release_if_needed(&_tmp299);
        _tmp293 = hml_val_bool(hml_to_bool(_tmp297));
        hml_release_if_needed(&_tmp297);
    }
    hml_release_if_needed(&_tmp294);
    int _tmp300 = hml_to_bool(_tmp293);
    hml_release(&_tmp293);
    if (_tmp300) {
        {
            HmlValue _tmp301 = hml_val_string("MappedFile.write_u8: offset out of bounds");
            hml_throw(_tmp301);
        }
    }
    HmlValue _tmp305 = hml_self;
    hml_retain_if_needed(&_tmp305);
    HmlValue _tmp304 = hml_object_get_field_required(_tmp305, "ptr");
    hml_release(&_tmp305);
    HmlValue _tmp306 = offset;
    hml_retain_if_needed(&_tmp306);
    HmlValue _tmp307 = hml_val_i32(1);
    HmlValue _tmp303 = hml_builtin_ptr_offset(NULL, _tmp304, _tmp306, _tmp307);
    hml_release(&_tmp304);
    hml_release(&_tmp306);
    hml_release(&_tmp307);
    HmlValue _tmp308 = val;
    hml_retain_if_needed(&_tmp308);
    HmlValue _tmp302 = hml_builtin_ptr_write_u8(NULL, _tmp303, _tmp308);
    hml_release(&_tmp303);
    hml_release(&_tmp308);
    hml_release(&_tmp302);
    hml_release(&_v__mode);
    hml_release(&_size);
    HML_CALL_EXIT();
    return hml_val_null();
}

HmlValue hml_fn_anon_15(HmlClosureEnv *_closure_env, HmlValue offset, HmlValue val) {
    HmlValue _v__mode = hml_closure_env_get(_closure_env, 7);
    HmlValue _size = hml_closure_env_get(_closure_env, 0);
    HML_CALL_ENTER();
    HmlValue _tmp310 = _v__mode;
    hml_retain_if_needed(&_tmp310);
    HmlValue _tmp311 = hml_val_string("rw");
    HmlValue _tmp309 = hml_both_i32(_tmp310, _tmp311) ? hml_i32_ne(_tmp310, _tmp311) : (hml_both_i64(_tmp310, _tmp311) ? hml_i64_ne(_tmp310, _tmp311) : hml_binary_op(HML_OP_NOT_EQUAL, _tmp310, _tmp311));
    hml_release_if_needed(&_tmp310);
    hml_release_if_needed(&_tmp311);
    int _tmp312 = hml_to_bool(_tmp309);
    hml_release(&_tmp309);
    if (_tmp312) {
        {
            HmlValue _tmp313 = hml_val_string("MappedFile.write_i32: file not opened in rw mode");
            hml_throw(_tmp313);
        }
    }
    HmlValue _tmp316 = offset;
    hml_retain_if_needed(&_tmp316);
    HmlValue _tmp317 = hml_val_i32(0);
    HmlValue _tmp315 = hml_both_i32(_tmp316, _tmp317) ? hml_i32_lt(_tmp316, _tmp317) : (hml_both_i64(_tmp316, _tmp317) ? hml_i64_lt(_tmp316, _tmp317) : hml_binary_op(HML_OP_LESS, _tmp316, _tmp317));
    hml_release_if_needed(&_tmp316);
    hml_release_if_needed(&_tmp317);
    HmlValue _tmp314;
    if (hml_to_bool(_tmp315)) {
        _tmp314 = hml_val_bool(1);
    } else {
        HmlValue _tmp320 = offset;
        hml_retain_if_needed(&_tmp320);
        HmlValue _tmp321 = hml_val_i32(4);
        HmlValue _tmp319 = hml_both_i32(_tmp320, _tmp321) ? hml_i32_add(_tmp320, _tmp321) : (hml_both_i64(_tmp320, _tmp321) ? hml_i64_add(_tmp320, _tmp321) : hml_binary_op(HML_OP_ADD, _tmp320, _tmp321));
        hml_release_if_needed(&_tmp320);
        hml_release_if_needed(&_tmp321);
        HmlValue _tmp322 = _size;
        hml_retain_if_needed(&_tmp322);
        HmlValue _tmp318 = hml_both_i32(_tmp319, _tmp322) ? hml_i32_gt(_tmp319, _tmp322) : (hml_both_i64(_tmp319, _tmp322) ? hml_i64_gt(_tmp319, _tmp322) : hml_binary_op(HML_OP_GREATER, _tmp319, _tmp322));
        hml_release_if_needed(&_tmp319);
        hml_release_if_needed(&_tmp322);
        _tmp314 = hml_val_bool(hml_to_bool(_tmp318));
        hml_release_if_needed(&_tmp318);
    }
    hml_release_if_needed(&_tmp315);
    int _tmp323 = hml_to_bool(_tmp314);
    hml_release(&_tmp314);
    if (_tmp323) {
        {
            HmlValue _tmp324 = hml_val_string("MappedFile.write_i32: offset out of bounds");
            hml_throw(_tmp324);
        }
    }
    HmlValue _tmp328 = hml_self;
    hml_retain_if_needed(&_tmp328);
    HmlValue _tmp327 = hml_object_get_field_required(_tmp328, "ptr");
    hml_release(&_tmp328);
    HmlValue _tmp329 = offset;
    hml_retain_if_needed(&_tmp329);
    HmlValue _tmp330 = hml_val_i32(1);
    HmlValue _tmp326 = hml_builtin_ptr_offset(NULL, _tmp327, _tmp329, _tmp330);
    hml_release(&_tmp327);
    hml_release(&_tmp329);
    hml_release(&_tmp330);
    HmlValue _tmp331 = val;
    hml_retain_if_needed(&_tmp331);
    HmlValue _tmp325 = hml_builtin_ptr_write_i32(NULL, _tmp326, _tmp331);
    hml_release(&_tmp326);
    hml_release(&_tmp331);
    hml_release(&_tmp325);
    hml_release(&_v__mode);
    hml_release(&_size);
    HML_CALL_EXIT();
    return hml_val_null();
}

HmlValue hml_fn_anon_16(HmlClosureEnv *_closure_env) {
    HML_CALL_ENTER();
    HmlValue _tmp333 = _main_mmap_sync;
    hml_retain_if_needed(&_tmp333);
    HmlValue _tmp336 = hml_self;
    hml_retain_if_needed(&_tmp336);
    HmlValue _tmp335 = hml_object_get_field_required(_tmp336, "ptr");
    hml_release(&_tmp336);
    HmlValue _args334[1];
    _args334[0] = _tmp335;
    HmlValue _tmp332 = hml_call_function(_tmp333, _args334, 1);
    hml_release(&_tmp335);
    hml_release(&_tmp333);
    HML_CALL_EXIT();
    return _tmp332;
    HML_CALL_EXIT();
    return hml_val_null();
}

HmlValue hml_fn_anon_17(HmlClosureEnv *_closure_env, HmlValue advice) {
    HML_CALL_ENTER();
    HmlValue _tmp338 = _main_mmap_advise;
    hml_retain_if_needed(&_tmp338);
    HmlValue _tmp341 = hml_self;
    hml_retain_if_needed(&_tmp341);
    HmlValue _tmp340 = hml_object_get_field_required(_tmp341, "ptr");
    hml_release(&_tmp341);
    HmlValue _tmp342 = advice;
    hml_retain_if_needed(&_tmp342);
    HmlValue _args339[2];
    _args339[0] = _tmp340;
    _args339[1] = _tmp342;
    HmlValue _tmp337 = hml_call_function(_tmp338, _args339, 2);
    hml_release(&_tmp340);
    hml_release(&_tmp342);
    hml_release(&_tmp338);
    HML_CALL_EXIT();
    return _tmp337;
    HML_CALL_EXIT();
    return hml_val_null();
}

HmlValue hml_fn_anon_18(HmlClosureEnv *_closure_env) {
    HML_CALL_ENTER();
    HmlValue _tmp344 = _main_mmap_close;
    hml_retain_if_needed(&_tmp344);
    HmlValue _tmp347 = hml_self;
    hml_retain_if_needed(&_tmp347);
    HmlValue _tmp346 = hml_object_get_field_required(_tmp347, "ptr");
    hml_release(&_tmp347);
    HmlValue _args345[1];
    _args345[0] = _tmp346;
    HmlValue _tmp343 = hml_call_function(_tmp344, _args345, 1);
    hml_release(&_tmp346);
    hml_release(&_tmp344);
    HML_CALL_EXIT();
    return _tmp343;
    HML_CALL_EXIT();
    return hml_val_null();
}

// Named function implementations
HmlValue hml_fn_MappedFile(HmlClosureEnv *_closure_env, HmlValue path, HmlValue mode) {
    (void)_closure_env;
    if (mode.type == HML_VAL_NULL) {
        HmlValue _tmp0 = hml_val_string("r");
        mode = _tmp0;
    }
    HML_CALL_ENTER();
    int _tail_depth = 0;
    _L0:;  // tail call target
    HmlClosureEnv *_shared_env_1 = hml_closure_env_new(13);
    HmlValue _tmp3 = _main_mmap_open;
    hml_retain_if_needed(&_tmp3);
    HmlValue _tmp5 = path;
    hml_retain_if_needed(&_tmp5);
    HmlValue _tmp6 = mode;
    hml_retain_if_needed(&_tmp6);
    HmlValue _args4[2];
    _args4[0] = _tmp5;
    _args4[1] = _tmp6;
    HmlValue _tmp2 = hml_call_function(_tmp3, _args4, 2);
    hml_release(&_tmp5);
    hml_release(&_tmp6);
    hml_release(&_tmp3);
    HmlValue _ptr = _tmp2;
    HmlValue _tmp8 = _ptr;
    hml_retain_if_needed(&_tmp8);
    HmlValue _tmp9 = hml_val_null();
    HmlValue _tmp7 = hml_both_i32(_tmp8, _tmp9) ? hml_i32_eq(_tmp8, _tmp9) : (hml_both_i64(_tmp8, _tmp9) ? hml_i64_eq(_tmp8, _tmp9) : hml_binary_op(HML_OP_EQUAL, _tmp8, _tmp9));
    hml_release_if_needed(&_tmp8);
    hml_release_if_needed(&_tmp9);
    int _tmp10 = hml_to_bool(_tmp7);
    hml_release(&_tmp7);
    if (_tmp10) {
        {
            HmlValue _tmp12 = hml_val_string("MappedFile: failed to map '");
            HmlValue _tmp13 = path;
            hml_retain_if_needed(&_tmp13);
            HmlValue _tmp14 = hml_val_string("'");
            HmlValue _tmp11 = hml_string_concat3(_tmp12, _tmp13, _tmp14);
            hml_release_if_needed(&_tmp12);
            hml_release_if_needed(&_tmp13);
            hml_release_if_needed(&_tmp14);
            hml_throw(_tmp11);
        }
    }
    HmlValue _tmp16 = _main_mmap_size;
    hml_retain_if_needed(&_tmp16);
    HmlValue _tmp18 = _ptr;
    hml_retain_if_needed(&_tmp18);
    HmlValue _args17[1];
    _args17[0] = _tmp18;
    HmlValue _tmp15 = hml_call_function(_tmp16, _args17, 1);
    hml_release(&_tmp18);
    hml_release(&_tmp16);
    HmlValue _size = _tmp15;
    HmlValue _tmp19 = mode;
    hml_retain_if_needed(&_tmp19);
    HmlValue _v__mode = _tmp19;
    HmlValue _tmp20 = hml_val_object();
    HmlValue _tmp21 = _ptr;
    hml_retain_if_needed(&_tmp21);
    hml_object_set_field(_tmp20, "ptr", _tmp21);
    hml_release(&_tmp21);
    HmlValue _tmp22 = _size;
    hml_retain_if_needed(&_tmp22);
    hml_object_set_field(_tmp20, "size", _tmp22);
    hml_release(&_tmp22);
    hml_closure_env_set(_shared_env_1, 0, _size);
    hml_closure_env_retain(_shared_env_1);
    HmlValue _tmp23 = hml_val_function_with_env_rest((void*)hml_fn_anon_0, (void*)_shared_env_1, 1, 1, 0, 0);
    const char *_param_names24[1] = {
"offset"    };
    hml_function_set_param_names(_tmp23, _param_names24, 1);
    hml_object_set_field(_tmp20, "read_u8", _tmp23);
    hml_release(&_tmp23);
    hml_closure_env_set(_shared_env_1, 0, _size);
    hml_closure_env_retain(_shared_env_1);
    HmlValue _tmp25 = hml_val_function_with_env_rest((void*)hml_fn_anon_1, (void*)_shared_env_1, 1, 1, 0, 0);
    const char *_param_names26[1] = {
"offset"    };
    hml_function_set_param_names(_tmp25, _param_names26, 1);
    hml_object_set_field(_tmp20, "read_i32", _tmp25);
    hml_release(&_tmp25);
    hml_closure_env_set(_shared_env_1, 0, _size);
    hml_closure_env_retain(_shared_env_1);
    HmlValue _tmp27 = hml_val_function_with_env_rest((void*)hml_fn_anon_2, (void*)_shared_env_1, 1, 1, 0, 0);
    const char *_param_names28[1] = {
"offset"    };
    hml_function_set_param_names(_tmp27, _param_names28, 1);
    hml_object_set_field(_tmp20, "read_i64", _tmp27);
    hml_release(&_tmp27);
    hml_closure_env_set(_shared_env_1, 0, _size);
    hml_closure_env_retain(_shared_env_1);
    HmlValue _tmp29 = hml_val_function_with_env_rest((void*)hml_fn_anon_3, (void*)_shared_env_1, 1, 1, 0, 0);
    const char *_param_names30[1] = {
"offset"    };
    hml_function_set_param_names(_tmp29, _param_names30, 1);
    hml_object_set_field(_tmp20, "read_f64", _tmp29);
    hml_release(&_tmp29);
    hml_closure_env_set(_shared_env_1, 7, _v__mode);
    hml_closure_env_set(_shared_env_1, 0, _size);
    hml_closure_env_retain(_shared_env_1);
    HmlValue _tmp31 = hml_val_function_with_env_rest((void*)hml_fn_anon_4, (void*)_shared_env_1, 2, 2, 0, 0);
    const char *_param_names32[2] = {
"offset", "val"    };
    hml_function_set_param_names(_tmp31, _param_names32, 2);
    hml_object_set_field(_tmp20, "write_u8", _tmp31);
    hml_release(&_tmp31);
    hml_closure_env_set(_shared_env_1, 7, _v__mode);
    hml_closure_env_set(_shared_env_1, 0, _size);
    hml_closure_env_retain(_shared_env_1);
    HmlValue _tmp33 = hml_val_function_with_env_rest((void*)hml_fn_anon_5, (void*)_shared_env_1, 2, 2, 0, 0);
    const char *_param_names34[2] = {
"offset", "val"    };
    hml_function_set_param_names(_tmp33, _param_names34, 2);
    hml_object_set_field(_tmp20, "write_i32", _tmp33);
    hml_release(&_tmp33);
    HmlValue _tmp35 = hml_val_function_rest((void*)hml_fn_anon_6, 0, 0, 0, 0);
    hml_object_set_field(_tmp20, "sync", _tmp35);
    hml_release(&_tmp35);
    HmlValue _tmp36 = hml_val_function_rest((void*)hml_fn_anon_7, 1, 1, 0, 0);
    const char *_param_names37[1] = {
"advice"    };
    hml_function_set_param_names(_tmp36, _param_names37, 1);
    hml_object_set_field(_tmp20, "advise", _tmp36);
    hml_release(&_tmp36);
    HmlValue _tmp38 = hml_val_function_rest((void*)hml_fn_anon_8, 0, 0, 0, 0);
    hml_object_set_field(_tmp20, "close", _tmp38);
    hml_release(&_tmp38);
    hml_release(&_ptr);
    hml_release(&_size);
    hml_release(&_v__mode);
    hml_closure_env_release(_shared_env_1);
    HML_CALL_EXIT();
    return _tmp20;
    hml_release(&_ptr);
    hml_release(&_size);
    hml_release(&_v__mode);
    hml_closure_env_release(_shared_env_1);
    HML_CALL_EXIT();
    return hml_val_null();
}

int main(int argc, char **argv) {
    hml_runtime_init(argc, argv);

    _main_args = hml_get_args();



    HmlValue _tmp39 = hml_val_function((void*)hml_builtin_mmap_open, 1, 2, 0);
    hml_retain_if_needed(&_tmp39);
    _main_mmap_open = _tmp39;
    HmlValue _tmp40 = hml_val_function((void*)hml_builtin_mmap_open_anon, 1, 1, 0);
    hml_retain_if_needed(&_tmp40);
    _main_mmap_open_anon = _tmp40;
    HmlValue _tmp41 = hml_val_function((void*)hml_builtin_mmap_sync, 1, 1, 0);
    hml_retain_if_needed(&_tmp41);
    _main_mmap_sync = _tmp41;
    HmlValue _tmp42 = hml_val_function((void*)hml_builtin_mmap_close, 1, 1, 0);
    hml_retain_if_needed(&_tmp42);
    _main_mmap_close = _tmp42;
    HmlValue _tmp43 = hml_val_function((void*)hml_builtin_mmap_size, 1, 1, 0);
    hml_retain_if_needed(&_tmp43);
    _main_mmap_size = _tmp43;
    HmlValue _tmp44 = hml_val_function((void*)hml_builtin_mmap_advise, 2, 2, 0);
    hml_retain_if_needed(&_tmp44);
    _main_mmap_advise = _tmp44;
    HmlValue _tmp45 = hml_val_function((void*)hml_builtin_mmap_protect, 2, 2, 0);
    hml_retain_if_needed(&_tmp45);
    _main_mmap_protect = _tmp45;
    HmlValue _tmp46 = hml_val_i32(PROT_NONE);
    hml_retain_if_needed(&_tmp46);
    _main_PROT_NONE = _tmp46;
    HmlValue _tmp47 = hml_val_i32(PROT_READ);
    hml_retain_if_needed(&_tmp47);
    _main_PROT_READ = _tmp47;
    HmlValue _tmp48 = hml_val_i32(PROT_WRITE);
    hml_retain_if_needed(&_tmp48);
    _main_PROT_WRITE = _tmp48;
    HmlValue _tmp49 = hml_val_i32(PROT_EXEC);
    hml_retain_if_needed(&_tmp49);
    _main_PROT_EXEC = _tmp49;
    HmlValue _tmp50 = hml_val_i32(MADV_NORMAL);
    hml_retain_if_needed(&_tmp50);
    _main_MADV_NORMAL = _tmp50;
    HmlValue _tmp51 = hml_val_i32(MADV_SEQUENTIAL);
    hml_retain_if_needed(&_tmp51);
    _main_MADV_SEQUENTIAL = _tmp51;
    HmlValue _tmp52 = hml_val_i32(MADV_RANDOM);
    hml_retain_if_needed(&_tmp52);
    _main_MADV_RANDOM = _tmp52;
    HmlValue _tmp53 = hml_val_i32(MADV_WILLNEED);
    hml_retain_if_needed(&_tmp53);
    _main_MADV_WILLNEED = _tmp53;
    HmlValue _tmp54 = hml_val_i32(MADV_DONTNEED);
    hml_retain_if_needed(&_tmp54);
    _main_MADV_DONTNEED = _tmp54;
    HmlValue _tmp55 = hml_val_function_rest((void*)hml_fn_anon_9, 2, 1, 0, 0);
    const char *_param_names56[2] = {
"path", "mode"    };
    hml_function_set_param_names(_tmp55, _param_names56, 2);
    _main_MappedFile = _tmp55;

    hml_runtime_cleanup();
    return 0;
}
