/*
 * Generated by Hemlock Compiler
 */

#include "hemlock_runtime.h"
#include <setjmp.h>
#include <signal.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <poll.h>

// Signal constants
#define SIGINT_VAL 2
#define SIGTERM_VAL 15
#define SIGHUP_VAL 1
#define SIGQUIT_VAL 3
#define SIGABRT_VAL 6
#define SIGUSR1_VAL 10
#define SIGUSR2_VAL 12
#define SIGALRM_VAL 14
#define SIGCHLD_VAL 17
#define SIGPIPE_VAL 13
#define SIGCONT_VAL 18
#define SIGSTOP_VAL 19
#define SIGTSTP_VAL 20

// Built-in globals
static HmlValue _main_args = {0};

// Top-level function variables (static for closure access)
static HmlValue _main_double = {0};

// Top-level variables (static for function access)
static HmlValue _main_x = {0};
static HmlValue _main_name = {0};
static HmlValue _main_a = {0};
static HmlValue _main_b = {0};
static HmlValue _main_sum = {0};
static HmlValue _main_arr = {0};

// Closure forward declarations
HmlValue hml_fn_anon_0(HmlClosureEnv *_closure_env, HmlValue n);

// Named function forward declarations
HmlValue hml_fn_double(HmlClosureEnv *_closure_env, HmlValue n);

// Closure implementations
HmlValue hml_fn_anon_0(HmlClosureEnv *_closure_env, HmlValue n) {
    HML_CALL_ENTER();
    HmlValue _tmp38 = n;
    hml_retain_if_needed(&_tmp38);
    HmlValue _tmp39 = hml_val_i32(2);
    HmlValue _tmp37 = hml_both_i32(_tmp38, _tmp39) ? hml_i32_mul(_tmp38, _tmp39) : (hml_both_i64(_tmp38, _tmp39) ? hml_i64_mul(_tmp38, _tmp39) : hml_binary_op(HML_OP_MUL, _tmp38, _tmp39));
    hml_release_if_needed(&_tmp38);
    hml_release_if_needed(&_tmp39);
    HML_CALL_EXIT();
    return _tmp37;
    HML_CALL_EXIT();
    return hml_val_null();
}

// Named function implementations
HmlValue hml_fn_double(HmlClosureEnv *_closure_env, HmlValue n) {
    (void)_closure_env;
    HML_CALL_ENTER();
    HmlValue _tmp1 = n;
    hml_retain_if_needed(&_tmp1);
    HmlValue _tmp2 = hml_val_i32(2);
    HmlValue _tmp0 = hml_both_i32(_tmp1, _tmp2) ? hml_i32_mul(_tmp1, _tmp2) : (hml_both_i64(_tmp1, _tmp2) ? hml_i64_mul(_tmp1, _tmp2) : hml_binary_op(HML_OP_MUL, _tmp1, _tmp2));
    hml_release_if_needed(&_tmp1);
    hml_release_if_needed(&_tmp2);
    HML_CALL_EXIT();
    return _tmp0;
    HML_CALL_EXIT();
    return hml_val_null();
}

int main(int argc, char **argv) {
    hml_runtime_init(argc, argv);
    
    _main_args = hml_get_args();
    
    
    
    HmlValue _tmp3 = hml_val_i32(42);
    _main_x = _tmp3;
    HmlValue _tmp4 = hml_val_string("World");
    _main_name = _tmp4;
    HmlValue _tmp6 = hml_val_string("");
    HmlValue _tmp7 = hml_val_string("Hello, ");
    HmlValue _concat8 = hml_string_concat(_tmp6, _tmp7);
    hml_release(&_tmp6);
    hml_release(&_tmp7);
    _tmp6 = _concat8;
    HmlValue _tmp8 = _main_name;
    hml_retain_if_needed(&_tmp8);
    HmlValue _concat9 = hml_string_concat(_tmp6, _tmp8);
    hml_release(&_tmp6);
    hml_release(&_tmp8);
    _tmp6 = _concat9;
    HmlValue _tmp9 = hml_val_string("! Answer is ");
    HmlValue _concat10 = hml_string_concat(_tmp6, _tmp9);
    hml_release(&_tmp6);
    hml_release(&_tmp9);
    _tmp6 = _concat10;
    HmlValue _tmp10 = _main_x;
    hml_retain_if_needed(&_tmp10);
    HmlValue _concat11 = hml_string_concat(_tmp6, _tmp10);
    hml_release(&_tmp6);
    hml_release(&_tmp10);
    _tmp6 = _concat11;
    hml_print(_tmp6);
    hml_release(&_tmp6);
    HmlValue _tmp5 = hml_val_null();
    hml_release(&_tmp5);
    HmlValue _tmp11 = hml_val_i32(10);
    _main_a = _tmp11;
    HmlValue _tmp12 = hml_val_i32(20);
    _main_b = _tmp12;
    HmlValue _tmp14 = _main_a;
    hml_retain_if_needed(&_tmp14);
    HmlValue _tmp15 = _main_b;
    hml_retain_if_needed(&_tmp15);
    HmlValue _tmp13 = hml_both_i32(_tmp14, _tmp15) ? hml_i32_add(_tmp14, _tmp15) : (hml_both_i64(_tmp14, _tmp15) ? hml_i64_add(_tmp14, _tmp15) : hml_binary_op(HML_OP_ADD, _tmp14, _tmp15));
    hml_release_if_needed(&_tmp14);
    hml_release_if_needed(&_tmp15);
    _main_sum = _tmp13;
    HmlValue _tmp17 = hml_val_string("");
    HmlValue _tmp18 = hml_val_string("Sum: ");
    HmlValue _concat19 = hml_string_concat(_tmp17, _tmp18);
    hml_release(&_tmp17);
    hml_release(&_tmp18);
    _tmp17 = _concat19;
    HmlValue _tmp19 = _main_sum;
    hml_retain_if_needed(&_tmp19);
    HmlValue _concat20 = hml_string_concat(_tmp17, _tmp19);
    hml_release(&_tmp17);
    hml_release(&_tmp19);
    _tmp17 = _concat20;
    hml_print(_tmp17);
    hml_release(&_tmp17);
    HmlValue _tmp16 = hml_val_null();
    hml_release(&_tmp16);
    HmlValue _tmp20 = hml_val_array();
    HmlValue _tmp21 = hml_val_i32(1);
    hml_array_push(_tmp20, _tmp21);
    hml_release(&_tmp21);
    HmlValue _tmp22 = hml_val_i32(2);
    hml_array_push(_tmp20, _tmp22);
    hml_release(&_tmp22);
    HmlValue _tmp23 = hml_val_i32(3);
    hml_array_push(_tmp20, _tmp23);
    hml_release(&_tmp23);
    HmlValue _tmp24 = hml_val_i32(4);
    hml_array_push(_tmp20, _tmp24);
    hml_release(&_tmp24);
    HmlValue _tmp25 = hml_val_i32(5);
    hml_array_push(_tmp20, _tmp25);
    hml_release(&_tmp25);
    _main_arr = _tmp20;
    HmlValue _tmp27 = hml_val_string("");
    HmlValue _tmp28 = hml_val_string("Array length: ");
    HmlValue _concat29 = hml_string_concat(_tmp27, _tmp28);
    hml_release(&_tmp27);
    hml_release(&_tmp28);
    _tmp27 = _concat29;
    HmlValue _tmp30 = _main_arr;
    hml_retain_if_needed(&_tmp30);
    HmlValue _tmp29 = hml_call_method(_tmp30, "length", NULL, 0);
    hml_release(&_tmp30);
    HmlValue _concat31 = hml_string_concat(_tmp27, _tmp29);
    hml_release(&_tmp27);
    hml_release(&_tmp29);
    _tmp27 = _concat31;
    hml_print(_tmp27);
    hml_release(&_tmp27);
    HmlValue _tmp26 = hml_val_null();
    hml_release(&_tmp26);
    HmlValue _tmp31 = hml_val_function_rest((void*)hml_fn_anon_0, 1, 1, 0, 0);
    _main_double = _tmp31;
    HmlValue _tmp33 = hml_val_string("");
    HmlValue _tmp34 = hml_val_string("Double of 21: ");
    HmlValue _concat35 = hml_string_concat(_tmp33, _tmp34);
    hml_release(&_tmp33);
    hml_release(&_tmp34);
    _tmp33 = _concat35;
    HmlValue _tmp36 = hml_val_i32(21);
    HmlValue _tmp35 = hml_fn_double(NULL, _tmp36);
    hml_release(&_tmp36);
    HmlValue _concat37 = hml_string_concat(_tmp33, _tmp35);
    hml_release(&_tmp33);
    hml_release(&_tmp35);
    _tmp33 = _concat37;
    hml_print(_tmp33);
    hml_release(&_tmp33);
    HmlValue _tmp32 = hml_val_null();
    hml_release(&_tmp32);
    
    hml_runtime_cleanup();
    return 0;
}
