/*
 * Hemlock Version Header
 *
 * Centralized version information for all Hemlock components.
 * All components (interpreter, compiler, LSP) share this version.
 */

#ifndef HEMLOCK_VERSION_H
#define HEMLOCK_VERSION_H

#define HEMLOCK_VERSION_MAJOR 2
#define HEMLOCK_VERSION_MINOR 5
#define HEMLOCK_VERSION_PATCH 6

#define HEMLOCK_VERSION "2.5.6"
#define HEMLOCK_VERSION_STRING "Hemlock v" HEMLOCK_VERSION

/*
 * Version history:
 *   2.4.11 - Fix `obj[key] = value` (and any indexed assignment) leaking the RHS — the pervasive leak that LSan-on-the-real-CP finally pinned. The index-assignment codegen released the object and index temps (hml_release_if_needed) but never released the value temp: codegen_expr returns the RHS owned (+1), every setter (hml_object_set_field / set_field_coerce / array_set / string_index_assign / buffer_set / ptr_set) takes its OWN reference, so the RHS creation reference was orphaned — every indexed store leaked its value. @stdlib/sqlite query() does `row[col_name] = value` for every column of every row, so a server that queries its DB per request (the Witchgrid control-plane: nodes_for_dashboard / compute_stats / etc. on every dashboard poll) bled GB; the per-CP-request leak was ~175 KB. Found by LSan-instrumenting the actual witchgrid-cp binary (emit-c + -fsanitize=address + a watchdog exit so LSan reports) and hammering it — the stacks named hml_cstr_to_string ← get_column_value ← query directly, ending a long synthetic-repro chase. Fix: release the RHS temp after the setter (it took its own ref), mirroring the array-literal `push; release(&elem)` pattern. Verified: a `row[k]=v` reproducer 560,056 → 56 bytes; parity 259/259; stress 6/6; new tests/stress/objset_leak.hml on the CI lsan lane. NOTE: a separate ~50 B/connection residual remains — accepted sockets are never freed (HmlSocket has no refcount; HML_VAL_SOCKET absent from hml_release, "OS resource shared by reference" by design); needs a socket-lifetime change, still tracked.
 *   2.4.10 - Fix every parsed JSON object leaking its entire tree (the real, dominant multi-GB Witchgrid control-plane bleed — the for-in fix in 2.4.9 was necessary but not the main CP leak). json_parse_object() hand-builds the HmlObject with malloc and sets 8 fields but never initialized is_pooled — so it held indeterminate stack/heap garbage. object_free() branches on `if (obj->is_pooled) obj_pool_free(obj); else free(...)`; with garbage is_pooled the foreign malloc'd object was routed into obj_pool_free() (which no-ops on non-pool blocks) and never freed — and the object pool freelist corrupted. Arrays were unaffected (no is_pooled), and object *literals* were fine (hml_val_object sets is_pooled=0); only the serializer's two hand-built object branches (empty-object and populated-object) were broken. Pinpointed by an HTTP-client+JSON LSan workload harness modelling the dashboard fan-out (outbound get + parse + traverse, per agent per poll): the leak was 2,679,006 bytes/1500 reqs and dropped ~36x to 75 KB after setting obj->is_pooled = 0 in both branches. Parity 259/259; stress 6/6. NOTE: the ~75 KB residual is a separate, much smaller (~50 B/connection) gap — accepted sockets (hml_socket_accept) are never freed because HmlSocket has no refcount and HML_VAL_SOCKET isn't in hml_release (sockets are "OS resource, shared by reference" by design); fixing it needs a socket-lifetime refcount change and is tracked next.
 *   2.4.9 - Fix the for-in iterable refcount leak for ALL iterable kinds — the actual multi-GB Witchgrid control-plane bleed. codegen_expr already returns an owned (+1) temporary for every iterable shape (idents/index/member get an hml_retain_if_needed'd copy, calls return their owned result, literals are freshly built); that +1 keeps the collection alive for the whole loop even if the body reassigns the source, and the single hml_release(&iter_val) at loop end balances it. The for-in additionally emitted its own hml_retain(&iter_val) with no second release, so every `for x in <iterable>` leaked the entire collection + contents on each execution. 2.4.7 removed the redundant retain only for the EXPR_CALL subcase (obj.keys()); idents, array/object/string literals, index and member iterables still leaked — e.g. `for tk in ts` once per request grew a server unbounded (the spawn/await path blamed in 2.4.8's note was a red herring: spawn/await itself is leak-clean; the tasks only leaked because the `ts` array holding them was leaked by its own for-in). Fix: drop the for-in's extra retain entirely; rely on codegen_expr's owned temp + the existing end-release. Verified with LSan: reproducers that leaked 64 KB–780 KB now hit the 56-byte clean baseline; parity 259/259; new tests/stress/forin_leak.hml guards ident/literal/keys/spawn-into-array shapes under the CI lsan lane.
 *   2.4.8 - Fix a silent infinite loop from a codegen state leak (correctness, not a leak — the scariest failure mode found in the audit). funcgen_add_params() set ctx->func_params for the function being generated, but FuncGenState's save/restore never tracked func_params/num_func_params/func_param_is_ref — so after ANY function body was generated, that function's parameter names stayed in ctx->func_params forever. codegen_is_func_param() is name-keyed and unscoped, so at top level it then reported those names as "function parameters". codegen_expr_ident gates the while-loop unboxing read path on `!codegen_is_func_param(name)`; with the stale entry, a top-level `while (n < 5) { n = n + 1 }` whose counter happened to share a name with some function's parameter (e.g. a defined-but-maybe-uncalled `fn f(n: i64)`) had its in-loop reads of `n` fall back to the boxed `_main_n` while the unboxed local was still declared and only synced back AFTER the loop — so the condition read a never-updated value and spun forever. Fix: add func_params/num_func_params/func_param_is_ref to FuncGenState; funcgen_save_state saves + clears them, funcgen_restore_state restores them, so a function's params can never leak into the enclosing or top-level scope. Found while leak-hunting (an arg_leak repro named a param `n`); pinned by reading the emitted C. New parity test tests/parity/language/while_unbox_param_name_collision.hml (parity 259/259). NOTE: the spawn/await HmlTask-lifetime leak — the actual multi-GB Witchgrid CP bleed — is still open and tracked next in the codegen-ownership audit.
 *   2.4.7 - Fix a large refcount leak in `for k in obj.keys()` (and any `for x in <call>()`). Two compounding bugs, both pinpointed with the new LeakSanitizer stress lane: (1) codegen for-in always retained the iterable then released it once at loop end — net-zero, correct for a borrowed `for x in somevar`, but for an owned call temporary like obj.keys() the call's original +1 was never consumed, so the whole keys array + backing store leaked every iteration. Fixed: when the iterable is an EXPR_CALL the redundant retain is skipped so the single end-release consumes the call's owned reference (gated to EXPR_CALL — a call never returns a borrow, so no double-free risk; nothing aliases the temp so it can't be freed mid-loop). (2) hml_object_keys() pushed hml_val_string() temporaries into an array, but hml_array_push() RETAINS its argument, orphaning each string's rc=1 creation reference — so every key string leaked even after the array was freed. Fixed: release the temp after pushing. Net on a render loop calling caps_data.keys()/binaries.keys()/flags.keys() per request: leak went from ~1.7 MB / 24k allocations per 2000 renders to 0 (one benign one-time hml_get_args argv alloc remains, suppressed). A Witchgrid control-plane bled multiple MB/min through this exact path. Parity 258/258; new tests/stress/keys_leak.hml guards it under CI's lsan lane. NOTE: the lsan tooling also surfaced separate, larger pre-existing refcount leaks in the broader concurrency paths (e.g. concurrent obj[key]+string-concat) — tracked for an ongoing codegen-ownership audit; the lsan lane is deliberately scoped to *_leak.hml so a real regression isn't masked by known-unfixed leaks.
 *   2.4.6 - Fix the immortal ASCII-string pool being freed after exactly ~1,000,000 releases. The pre-allocated single-char string pool (init_ascii_strings) marked entries "immortal, never freed" by setting ref_count = 1000000 — but hml_retain/hml_release still did the normal atomic add/sub with no immortal check, so the sentinel was a countdown, not a freeze. Any program that materializes-then-releases single-char strings ~1e6 times — trivial for a busy server: every `"x" + s` allocates the pooled "x" and releases it — drove the count to 0, string_free()'d a pooled string the process-global cache still points at, and the next single-char string use was a heap-use-after-free in hml_string_concat (SIGSEGV / "double free"). This is the deeper bug noted in 2.4.5: it is NOT concurrency (reproduces single-threaded after enough iterations); the Witchgrid control-plane just reached the threshold every ~73 min under dashboard load. Fix: HML_REFCOUNT_IMMORTAL sentinel + HML_REFCOUNT_IMMORTAL_MIN threshold; hml_retain/hml_release now check the count *before* the atomic op and treat frozen objects as immovable — never incremented, never decremented, never freed. Pinpointed with an ASan-instrumented runtime build (the alloc/free/use stacks named init_ascii_strings directly). Verified: a 10,000,000-iteration single-char-concat reproducer that crashed at ~1-2M now survives; parity 258/258 unchanged.
 *   2.4.5 - Thread-safety fix: object field lookup is now lock-free read-only and never lazily mutates a shared object. object_lookup_field() used to build the hash table on first lookup ("if no hash table, object_hash_rebuild(obj)"); JSON-parsed and some literal-constructed objects reach readers with hash_table == NULL (see builtins_serialization.c "Lazy initialization"), so N concurrent obj[key] reads of the same shared object all entered the rebuild and raced on free(obj->hash_table)+malloc — heap corruption surfacing as "free(): double free / unaligned chunk" and SIGSEGV. Now the read path falls back to a lock-free linear scan when no hash table is present (objects are typically small; correctness over a micro-opt that corrupts the heap); the hash table is still built eagerly by set_field/delete_field for the mutation path's speed. Diagnosed via the 2.4.4 crash handler on a Witchgrid control-plane core-dumping every ~73 min: a JSON-parsed capabilities map indexed concurrently by spawn-per-request dashboard handler threads. NOTE: a separate, deeper issue remains — codegen refcount ownership for a module-global string used as a concat operand over-releases (and slow-leaks) it, crashing single-threaded after enough iterations; tracked separately, needs a careful codegen fix guarded by a concurrency stress / ThreadSanitizer harness.
 *   2.4.4 - Fatal-signal backtrace handler in the runtime. hml_runtime_init now installs handlers for SIGSEGV/SIGABRT/SIGBUS/SIGFPE/SIGILL that dump a symbolized backtrace (glibc backtrace_symbols_fd, async-signal-safe) to stderr, then restore the default disposition and re-raise so the original exit status / core-dump / systemd Restart= behavior is preserved exactly. The compiler now links binaries with -rdynamic (all link paths: Linux dynamic/static ±websockets, macOS) so the binary's own Hemlock functions resolve to names in the trace, not bare addresses — turns "systemd says status=11/SEGV, no idea where" into an actionable stack on the very first crash, with zero gdb/valgrind/coredump tooling required on the target box. Opt out with HML_NO_CRASH_HANDLER=1 (e.g. when a program installs its own SIGSEGV handler via the signal() builtin). Motivated by a Witchgrid control-plane that was core-dumping every ~73 min on a box with no debugger installed; the handler is what makes that diagnosable in-place.
 *   2.4.3 - Partial fixes for macOS-only sleep() timer coalescing on idle daemons. Improves but does not fully eliminate the kernel-level behavior where a quiet long-running process's sleep(N) calls return N to ~1000 seconds late. Three changes: (1) spawn'd-task threads now pin themselves to QOS_CLASS_USER_INITIATED via pthread_set_qos_class_self_np in builtins_async.c task_thread_wrapper — without this they inherit the process QoS and a launchd-spawned daemon can land in a coalesced class. (2) hml_runtime_init now resets nice to 0 via setpriority(PRIO_PROCESS, 0, 0) and pins the main thread's QoS, undoing the silent nice +5 that nohup adds on macOS shells (macOS auto-downgrades QoS for any process with positive nice, even though that fact isn't documented anywhere obvious). (3) hml_sleep on macOS now uses libdispatch's DISPATCH_TIMER_STRICT timer source — Apple's documented opt-out from coalescing — instead of nanosleep(). End-to-end this fixes the FIRST few minutes after a fresh launch (heartbeats fire on time, every interval, exactly as requested); after the process has been quiet for several minutes even DISPATCH_TIMER_STRICT gets stretched, indicating remaining throttling is process-level rather than per-thread/per-call. Verified end-to-end with a witchgrid-agent on M1 mac mini: clean 30s heartbeats post-launch, intermittent stalls thereafter.
 *   2.4.2 - Four macOS-only Hemlock bugs (all surfaced via a long-running HTTP server + async sqlite + periodic outbound HTTP, none reproduce on Linux). (1) @stdlib/sqlite.open_db() now passes SQLITE_OPEN_FULLMUTEX so the connection is safe to use from spawn'd handlers — macOS system libsqlite3 defaults to "multithread" (no internal serialization) and segfaults in sqlite3DbMallocRawNN when a query fires from another thread; Linux glibc happens to default to serialized so the same code worked there. New SQLITE_OPEN_NOMUTEX export for the explicit opt-out via open_db_flags(). (2) LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT is now set only once per process via a static once-flag — passing it on every lws_create_context (the natural pattern for one-shot HTTP requests) made the second context's lws_context_init_client_ssl fail and tear down the partially-built default vhost; on macOS that teardown closed pollfds in a way that corrupted unrelated TcpListener fds in other threads. (3) hml_socket_create / hml_socket_accept now F_DUPFD to >= 3 when the kernel returns a low fd. libwebsockets' Homebrew build pulls in LWS_WITH_PLUGINS_BUILTIN, which auto-loads sshd / raw-test demo protocols on first lws_create_context; those plugins close stdin when their config files are missing, so the next socket() lands on fd 0 — and the next lws context's default-vhost teardown closes fd 0 again, killing any HTTP-server listener that landed there (accept() spins on EBADF forever). (4) New hml_runtime_pin_stdio() re-pins /dev/null onto fds 0/1/2 if any are closed — called at runtime startup AND before every lws_create_context. Without this, lws's open of /dev/urandom landed on fd 0 (closed by the sshd plugin) and was rejected ("ZERO RANDOM FD"), leaving OpenSSL with a degraded entropy source that intermittently stalled SSL/TLS-adjacent setup for 3-9 minutes per call — outbound heartbeats from a witchgrid-agent went silent for minutes at a time before resuming.
 *   2.4.1 - Three follow-ons from Witchgrid agent-restart adoption work: TCP listener + accepted-client socket fds now set FD_CLOEXEC in hml_socket_create + hml_socket_accept (without this, posix_spawn'd children inherited the listener and held it alive across the parent's death, blocking same-port restart); new file.read_binary() on @stdlib/fs.open(...) returning a buffer to preserve nul bytes when reading /proc/<pid>/cmdline or other binary content (mirrors stream.read_binary from 2.3.1); exec_argv() gained a stdin option that pipes a string into the child's stdin via pipe(2), removing the `sh -c "cmd < file"` wrapper pattern. Plus the macOS Makefile pkg-config-fallback patch from the mac-build-docs branch (probes /opt/homebrew/include + /usr/local/include).
 *   2.4.0 - HTTP/auth + ergonomics batch (10 issues from Witchgrid bring-up): @stdlib/http now threads custom headers through POST/PUT/DELETE/PATCH and the timeout variants (was: only Content-Type made it to libwebsockets, breaking Authorization on POST); interpreter named-module imports are now live bindings instead of import-time snapshots so reassigning an exported `let` is visible to importers and to spawned tasks; flow null-narrowing propagates through `?.` field access (no more `let mp = model_path` shadow-rebind after a null check); type error labels report the parameter name instead of `'positional'`; `string.lower()`/`upper()` aliases for `to_lower`/`to_upper`; `get_binary` follows 3xx redirects (GitHub→CDN tarball pulls work directly); C codegen no longer prefixes call symbols with surrounding scope tokens (function calls inside `port_free_on_agent(agent_url: ...)` no longer mangle to `hml_fn_agent_*`); macOS libwebsockets initialization picks up Homebrew CA bundles by default (no SSL_CERT_FILE workaround); default one-shot LWS HTTP timeout lowered from ~30s to 5s so a single failed call doesn't wedge the caller for half a minute (the `_timeout` variants still honor their per-call timeout); side-effect import workaround documented
 *   2.3.1 - Binary HTTP fixes: @stdlib/http.download() now actually writes the buffer body (was f.write(buffer) which silently no-op'd in compiled binaries and threw in the interpreter); new download_streaming(url, path) for bounded-memory pulls of large files (model weights, archives) — chunks straight to disk via .partial + atomic rename; new stream.read_binary() + __lws_http_stream_read_binary returning buffer chunks (existing read() routes through val_string which strlen-truncates at the first 0x00 byte, corrupting binary payloads)
 *   2.3.0 - Streaming HTTP support in @stdlib/http (chunked / SSE): stream(), stream_get(), stream_post(), post_json_stream(), stream_sse(); compiler runtime now sends POST bodies for streaming requests and throws the same catchable errors as the interpreter (invalid ptr, bad URL, connection failure) for full interpreter/compiler parity
 *   2.2.3 - Patch release with runtime/compiler hardening: catchable socket connect/bind failures, correct /proc and /sys File.read() behavior, safer buffer memory builtins, optional-chain null-guard narrowing, string concatenation numeric regressions fixed, CLI help parsing fixed, and fs.make_dirs() added
 *   2.2.2 - Release prep with compiler/runtime/install hardening: catchable runtime file_stat() failures, typed-array fast-path assignment checks, non-default-prefix stdlib/runtime lookup fixes, and refreshed documentation audits
 *   2.2.1 - HTTP POST/PUT/PATCH/DELETE body fix: compiled binaries actually send Content-Type, Content-Length, and the body bytes (interpreter was already correct); libwebsockets startup banner suppressed by default in compiled binaries to match interpreter
 *   2.2.0 - posix_spawn() primitive in @stdlib/process; fs.open_fd()/fileno() for raw fd access; string-literal object keys and obj?[key] safe-index; FFI fix for two-library import collision; compiler-strictness parity fixes (typed array of custom types, `export let X = X;` self-rebind, substr() arity); incremental builds correctly track header dependencies
 *   2.1.1 - Parser no longer hangs on malformed `match { arm => { ... } }` when block arm is parsed as object literal and fails
 *   2.1.0 - HTTP client actually sends POST/PUT/PATCH bodies; @stdlib/json exports its public API for `import * as`
 *   2.0.3 - Fix compiler symbol collision when a module exports `init` (or any name shared with the module initializer)
 *   2.0.2 - Fix i32 overflow in HashMap djb2 string hash; accumulate in i64 + mask
 *   2.0.1 - Bugfix release since v2.0.0 (runtime/compiler correctness, stability, docs)
 *   2.0.0 - BREAKING: Move 63 builtins to stdlib modules, reducing global namespace conflicts
 *   1.10.0 - (skipped, became 2.0.0)
 *   1.9.4 - Fix fire-and-forget spawn, WebSocket server SO_REUSEADDR
 *   1.9.3 - WebSocket binary data support: __lws_msg_binary builtin, fix server send_binary, fix recv binary handler
 *   1.9.2 - Compiler fixes: unboxed loop counter boxing, clear() object dispatch, exec() import shadowing
 *   1.9.1 - QoL: write() builtin, single-arg slice(), rune join(), HashMap numeric key coercion
 *   1.9.0 - WASM interpreter release artifact, version bump for release
 *   1.8.8 - Fix compiler inlining bugs, ptr subtraction type checking, catchable open() exceptions
 *   1.8.7 - Fix multi-argument print/eprint in compiler codegen
 *   1.8.6 - Fix segfault in hml_string_append_inplace for SSO strings
 *   1.8.5 - 5 new array methods (every, some, indexOf, sort, fill), major performance optimizations, memory leak fixes
 *   1.8.4 - Graceful handling for reserved keywords (def, func, var, class), fix flaky CI tests
 *   1.8.3 - Code polish: consolidate magic numbers, standardize error messages
 *   1.8.2 - Memory leak prevention: exception-safe eval, task/channel cleanup, optimizer fixes
 *   1.8.1 - Fix use-after-free bug in function return value handling
 *   1.8.0 - Pattern matching, arena allocator, memory leak fixes
 *   1.7.5 - Fix formatter else-if indentation bug
 *   1.7.4 - Formatter improvements: function parameter, binary expr, import, and method chain line breaking
 *   1.7.3 - Fix formatter comment and blank line preservation
 *   1.7.2 - Maintenance release
 *   1.7.1 - Single-line if/while/for statements (braceless syntax)
 *   1.7.0 - Type aliases, function types, const params, method signatures, loop labels, named args, null coalescing
 *   1.6.7 - Octal literals, block comments, hex/unicode escapes, numeric separators
 *   1.6.6 - Float literals without leading zero, fix strength reduction bug
 *   1.6.5 - Fix for-in loop syntax without 'let' keyword
 *   1.6.4 - Hotfix release
 *   1.6.3 - Fix runtime method dispatch for file, channel, socket types
 *   1.6.2 - Patch release
 *   1.6.1 - Patch release
 *   1.6.0 - Compile-time type checking, LSP integration, bitwise operators
 *   1.5.0 - Full type system, async/await, atomics, 39 stdlib modules
 *   1.1.0 - Unified versioning across all components
 *   1.0.x - Initial release series (interpreter only)
 *   0.1.x - Pre-release compiler development
 */

#endif /* HEMLOCK_VERSION_H */
